(mes
 (meta (engine 'AI5) (charset "english") (dictbase 128))
 (dict
  #\u3000
  #\＜
  #\＞
  #\ー
  #\の
  #\タ
  #\ン
  #\ス
  #\デ
  #\る
  #\ト
  #\ィ
  #\？
  #\お
  #\ま
  #\け
  #\で
  #\み
  #\は
  #\ド
  #\モ
  #\戦
  #\闘)
 (define-proc 0
   (<>
    (set-arr~ @ 1 32768)
    (set-arr~ @ 7 0)
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (set-arr~ @ 6 0)
    (image "m_waku1.pd8")
    (cond
     ((== A 1) (<> (image "face01.pd8")))
     ((== A 2) (<> (image "face02.pd8")))
     ((== A 3) (<> (image "face03.pd8")))
     ((== A 4) (<> (image "face04.pd8")))
     ((== A 5) (<> (image "face05.pd8")))
     ((== A 6) (<> (image "face06.pd8")))
     ((== A 7) (<> (image "face07.pd8")))
     ((== A 8) (<> (image "face08.pd8")))
     ((== A 9) (<> (image "face09.pd8")))
     ((== A 10) (<> (image "face10.pd8")))
     ((== A 11) (<> (image "face11.pd8")))
     ((== A 12) (<> (image "face12.pd8")))
     ((== A 13) (<> (image "face13.pd8")))
     ((== A 14) (<> (image "face14.pd8")))
     ((== A 15) (<> (image "face15.pd8")))
     ((== A 16) (<> (image "face16.pd8")))
     ((== A 17) (<> (image "face17.pd8")))
     ((== A 18) (<> (image "face18.pd8")))
     ((== A 19) (<> (image "face19.pd8")))
     ((== A 20) (<> (image "face20.pd8")))
     ((== A 21) (<> (image "face21.pd8")))
     ((== A 22) (<> (image "face22.pd8")))
     ((== A 23) (<> (image "face23.pd8")))
     ((== A 24) (<> (image "face24.pd8")))
     ((== A 25) (<> (image "face25.pd8")))
     ((== A 26) (<> (image "face26.pd8")))
     ((== A 27) (<> (image "face27.pd8")))
     ((== A 28) (<> (image "face28.pd8")))
     ((== A 29) (<> (image "face29.pd8")))
     ((== A 30) (<> (image "face30.pd8")))
     ((== A 31) (<> (image "face31.pd8")))
     ((== A 32) (<> (image "face32.pd8")))
     ((== A 33) (<> (image "face33.pd8")))
     ((== A 34) (<> (image "face34.pd8")))
     ((== A 35) (<> (image "face35.pd8")))
     (else (<> (image "face35.pd8"))))
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 7 1)
    (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
    (set-arr~ @ 21 272)
    (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
    (set-arr~ @ 13 27 75 68 170)
    (color 8)
    (clear)
    (set-arr~ @ 1 4096)))
 (define-proc 1
   (<>
    (set-arr~ @ 1 32768)
    (set-arr~ @ 7 0)
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (set-arr~ @ 6 0)
    (image "m_waku2.pd8")
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 7 1)
    (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
    (set-arr~ @ 21 272)
    (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
    (set-arr~ @ 13 19 79 60 167)
    (color 8)
    (clear)
    (set-arr~ @ 1 4096)))
 (define-proc 3
   (<>
    (palette 3 0)
    (set-arr~ @ 7 0)
    (set-arr~ @ 13 0 0 79 399)
    (clear 0)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 0)
    (set-arr~ @ 1 0)))
 (define-proc 4
   (<>
    (set-arr~ @ 1 4096)
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (set-arr~ @ 13 4 312 75 (+ 312 (* 16 4)))
    (color 8)
    (set-arr~ @ 17 4 312)
    (set-arr~ @ 7 1)
    (palette 3)))
 (define-proc 5
   (<>
    (set-arr~ @ 1 4096)
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (set-arr~ @ 13 4 312 75 (+ 312 (* 16 4)))
    (color 8)
    (set-arr~ @ 17 4 312)
    (set-arr~ @ 7 1)))
 (define-proc 6
   (<>
    (set-arr~ @ 7 0)
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (set-arr~ @ 6 1)
    (set-arr~ @ 1 0)))
 (define-proc 7 (<> (set-arr~ @ 6 0) (set-arr~ @ 1 4096) (set-arr~ @ 7 1)))
 (define-proc 12
   (<>
    (set-arr~ @ 6 1)
    (set-var K (/ K 2))
    (color 16)
    (box 37 386 79 399)
    (if (> (/ K 8) 0) (<> (color 144) (box 37 386 (- (+ 37 (/ K 8)) 1) 399)))
    (if (!= K 0)
      (<>
       (blit-mask
        (- (+ 45 7) (% K 8))
        372
        (- (+ 45 7) (% K 8))
        385
        1
        (+ 37 (/ K 8))
        386
        1)))
    (blit 37 386 79 399 1 32 (+ 306 (* 3 18)) 0)))
 (define-proc 26
   (<>
    (set-arr~ @ 9 (// (~ @ 9) 8))
    (call (+ (~ @ 0) (* 86 2)))
    (set-arr~ @ 9 (&& (~ @ 9) 65527))))
 ((sys 32) 0 (<>))
 ((sys 32) 1 (<> (set-var C 0) (mes-call "camp.mes")))
 (if (== (: 1023) 1) (<> (set-var C 5) (mes-call "camp.mes")))
 (set-arr~ @ 9 (// (~ @ 9) 1))
 (set-arr~ @ 9 (// (~ @ 9) 4))
 (set-arr~ @ 7 1)
 (slot 3
   (<>
    (palette 3 0)
    (set-arr~ @ 13 0 0 79 399)
    (color 7)
    (clear)
    (set-arr~ @ 1 32768)
    (set-arr~ @ 7 0)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 6 0)
    (image "m_waku1.pd8")
    (image "face10.pd8")
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 7 1)
    (palette 3)
    (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
    (set-arr~ @ 21 272)
    (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
    (set-arr~ @ 13 27 75 68 170)
    (color 8)
    (text-color 7)
    (clear)
    (set-arr~ @ 1 4096)))
 (define-proc 0
   (<>
    (set-arr~ @ 7 0)
    (define-proc 30
      (<>
       (box-inv
        24
        (+ (- 328 36) (* (~ @ 23) 18))
        53
        (+ (- 328 36) (* (~ @ 23) 18) 15))))
    (define-proc 31 (<> (proc 30)))
    (define-proc 32
      (<>
       (set-var J (~ @ 22))
       (set-var S (~ J (+ (* (~ @ 23) 2) 1)))
       (set-arr~ @ 27 0)))
    (define-proc 33
      (<> (if (!= (: 0) 0) (<> (set-var S 0) (set-arr~ @ 27 0)))))
    (define-proc 34
      (<>
       (if-else (!= (~ @ 23) 0)
         (<> (proc 31) (set-arr~ @ 23 (- (~ @ 23) 1)) (proc 30))
         (<>
          (if (!= (~ @ 24) 0)
            (<>
             (set-arr~ @ 24 (- (~ @ 24) 1))
             (menu-init 0)
             (color 71)
             (set-var I 0)
             (while
              (!= I (~ @ 25))
              (<>
               (box 24 (+ (- 328 36) (* I 18)) 53 (+ (- 328 36) (* I 18) 15))
               (set-var J (~ @ 22))
               (if (!= (~ J (+ (* I 2) 1)) 0)
                 (<>
                  (set-arr~ @ 17 24 (+ (- 328 36) (* I 18)))
                  (call (~ J (* I 2)))))
               (set-var I (+ I 1))))
             (color 112)
             (proc 30)))))))
    (define-proc 35
      (<>
       (set-var J (~ @ 22))
       (if-else (&&
                 (!= (~ J (+ (* (+ (~ @ 23) 1) 2) 1)) 0)
                 (!= (~ @ 23) (- (~ @ 25) 1)))
         (<> (proc 31) (set-arr~ @ 23 (+ (~ @ 23) 1)) (proc 30))
         (<>
          (if (> (~ @ 26) (+ (~ @ 25) (~ @ 24)))
            (<>
             (set-arr~ @ 24 (+ (~ @ 24) 1))
             (menu-init 0)
             (color 71)
             (set-var I 0)
             (while
              (!= I (~ @ 25))
              (<>
               (box 24 (+ (- 328 36) (* I 18)) 53 (+ (- 328 36) (* I 18) 15))
               (set-var J (~ @ 22))
               (if (!= (~ J (+ (* I 2) 1)) 0)
                 (<>
                  (set-arr~ @ 17 24 (+ (- 328 36) (* I 18)))
                  (call (~ J (* I 2)))))
               (set-var I (+ I 1))))
             (color 112)
             (proc 30)))))))
    (define-proc 36 (<>))
    (define-proc 37 (<>))
    (define-proc 38
      (<>
       (set-arr~ @ 25 (: 1))
       (set-arr~ @ 24 0)
       (set-arr~ @ 23 0)
       (menu-init 1)
       (menu-init 0)
       (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
       (set-arr~ @ 21 272)
       (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
       (set-arr~ @ 13 0 0 79 399)
       (color 71)
       (set-var I 0)
       (while
        (!= I (~ @ 25))
        (<>
         (box 24 (+ (- 328 36) (* I 18)) 53 (+ (- 328 36) (* I 18) 15))
         (set-var J (~ @ 22))
         (if (!= (~ J (+ (* I 2) 1)) 0)
           (<>
            (set-arr~ @ 17 24 (+ (- 328 36) (* I 18)))
            (call (~ J (* I 2)))))
         (set-var I (+ I 1))))
       (color 112)
       (proc 30)
       (if (== (: 0) 0) (<> (palette 3)))))
    (define-proc 39 (<>))))
 (if (== (: 1008) 0)
   (<>
    (palette 3 0)
    (set-arr~ @ 7 0)
    (set-arr~ @ 6 0)
    (palette 3 0)
    (set-arr~ @ 13 0 0 79 399)
    (color 7)
    (clear)
    (set-arr~ @ 1 32768)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (image "rogo.pd8")
    (blit 0 36 79 399 0 0 0 0)
    (set-reg: 0 0)
    (set-reg: 1 5)
    (proc 0)
    (menu-show
     (<.>
      (text "Use Save Data 1 for the Extra　　")
      (text "Use Save Data 2 for the Extra　　")
      (text "Use Save Data 3 for the Extra　　")
      (text "Use Save Data 4 for the Extra　　")
      (text "Use Save Data 5 for the Extra　　")))
    (cond
     ((== S 2) (<> (flag 2 1)))
     ((== S 3) (<> (flag 2 2)))
     ((== S 4) (<> (flag 2 3)))
     ((== S 5) (<> (flag 2 4)))
     (else (<> (flag 2 0))))
    (set-reg: 1008 1)
    (mes-jump "omake.mes")))
 (while
  (== 1 1)
  (<>
   (palette 3 0)
   (set-arr~ @ 7 0)
   (set-arr~ @ 6 0)
   (palette 3 0)
   (set-arr~ @ 13 0 0 79 399)
   (color 7)
   (clear)
   (set-arr~ @ 1 32768)
   (set-arr~ @ 9 (&& (~ @ 9) 65534))
   (image "rogo.pd8")
   (blit 0 36 79 399 0 0 0 0)
   (set-reg: 0 0)
   (set-reg: 1 3)
   (proc 0)
   (menu-show
    (<.> (text "Meet the Girls in the Game　　　") (text "MUSIC MODE　　　　") (text "Back to the Game")))
   (cond
    ((== S 1)
     (<>
      (if (== (: 210) 1)
        (<>
         (slot 1 1)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e088.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e088an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e088.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 6 0)
         (animate 1 6)
         (animate 0 2 1)
         (animate 1 2)
         (animate 0 4 2)
         (animate 1 4)
         (delay)))
      (if (== (: 380) 1)
        (<>
         (slot 1 1)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e050.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e050an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e050.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 6 0)
         (animate 1 6)
         (animate 0 4 1)
         (animate 1 4)
         (delay)))
      (if (== (: 409) 1)
        (<>
         (slot 1 1)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e070.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e070an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e070.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 3 0)
         (animate 1 3)
         (delay)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e071.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e071an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e071.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 3 0)
         (animate 1 3)
         (delay)))
      (if (== (: 384) 1)
        (<>
         (slot 1 1)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e056.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e056an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e056.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 6 0)
         (animate 1 6)
         (delay)))
      (if (== (: 400) 1)
        (<>
         (slot 1 1)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e062.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e062an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e062.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 6 0)
         (animate 1 6)
         (delay)))
      (if (== (: 401) 1)
        (<>
         (slot 1 1)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e057.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e057an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e057.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 6 0)
         (animate 1 6)
         (delay)))
      (if (== (: 402) 1)
        (<>
         (slot 1 1)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e058.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e058an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e058.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 6 0)
         (animate 1 6)
         (delay)))
      (if (== (: 403) 1)
        (<>
         (slot 1 1)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e059.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e059an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e059.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 6 0)
         (animate 1 6)
         (delay)))
      (if (== (: 404) 1)
        (<>
         (slot 1 1)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e060.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e060an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e060.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 6 0)
         (animate 1 6)
         (delay)))
      (if (== (: 405) 1)
        (<>
         (slot 1 1)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e061.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e061an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e061.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 6 0)
         (animate 1 6)
         (delay)))
      (if (== (: 319) 1)
        (<>
         (slot 1 2)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e042.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e042an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e042.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 6 0)
         (animate 1 6)
         (delay)
         (set-arr~ @ 7 0)
         (set-arr~ @ 9 (&& (~ @ 9) 65534))
         (set-arr~ @ 6 0)
         (set-arr~ @ 1 0)
         (set-arr~ @ 12 2)
         (image "e042k.pd8")
         (set-arr~ @ 1 4096)
         (set-arr~ @ 9 (// (~ @ 9) 1))
         (set-arr~ @ 13 4 312 75 (+ 312 (* 16 4)))
         (text-color 7)
         (clear)
         (set-arr~ @ 7 1)
         (animate 0 6 1)
         (animate 1 6)
         (delay)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e043.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e043an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e043.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 6 0)
         (animate 1 6)
         (delay)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e044.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e044an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e044.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 6 0)
         (animate 1 6)
         (delay)))
      (if (== (: 274) 1)
        (<>
         (slot 1 2)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e087.pd8")
         (proc 4)
         (delay)))
      (if (== (: 390) 1)
        (<>
         (slot 1 2)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e063.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e063an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e063.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 0 0)
         (animate 1 0)
         (delay)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e064.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e064an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e064.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 3 0)
         (animate 1 3)
         (delay)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e065.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e065an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e065.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 3 0)
         (animate 1 3)
         (delay)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e066.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e066an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e066.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 3 0)
         (animate 1 3)
         (delay)))
      (if (== (: 348) 1)
        (<>
         (slot 1 2)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e048.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e048an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e048.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 7 0)
         (animate 1 7)
         (delay)))
      (if (== (: 109) 1)
        (<>
         (slot 1 3)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e002.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e002an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e002.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 5 0)
         (animate 1 5)
         (animate 0 1 1)
         (animate 1 1)
         (animate 0 3 2)
         (animate 1 3)
         (animate 0 4 3)
         (animate 1 4)
         (animate 0 6 4)
         (animate 1 6)
         (delay)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e004.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e004an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e004.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 3 0)
         (animate 1 3)
         (delay)))
      (if (== (: 155) 1)
        (<>
         (slot 1 3)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e010.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e010an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e010.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 6 0)
         (animate 1 6)
         (animate 0 5 1)
         (animate 1 6)
         (delay)))
      (if (== (: 156) 1)
        (<>
         (slot 1 3)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e011.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e011an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e011.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 6 0)
         (animate 1 6)
         (delay)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e013.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e013an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e013.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 6 0)
         (animate 1 6)
         (delay)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e012.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e012an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e012.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 6 0)
         (animate 1 6)
         (animate 0 0 1)
         (animate 1 0)
         (delay)))
      (if (== (: 167) 1)
        (<>
         (slot 1 3)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e015.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e015an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e015.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 1 0)
         (animate 1 1)
         (animate 0 2 1)
         (animate 1 2)
         (animate 0 4 2)
         (animate 1 4)
         (animate 0 5 3)
         (animate 1 5)
         (animate 0 6 4)
         (animate 1 6)
         (animate 0 0 5)
         (animate 1 0)
         (delay)))
      (if (== (: 192) 1)
        (<>
         (slot 1 3)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e016.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e016an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e016.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 3 0)
         (animate 1 3)
         (delay)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e017.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e017an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e017.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 3 0)
         (animate 1 3)
         (delay)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e018.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e018an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e018.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 3 0)
         (animate 1 3)
         (delay)))
      (if (== (: 201) 1)
        (<>
         (slot 1 3)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e020.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e020an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e020.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 3 0)
         (animate 1 3)
         (animate 0 0 1)
         (animate 1 0)
         (delay)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e021.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e021an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e021.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 3 0)
         (animate 1 3)
         (delay)))
      (if (== (: 360) 1)
        (<>
         (slot 1 3)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e051.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e051an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e051.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 6 0)
         (animate 1 6)
         (delay)))
      (if (== (: 372) 1)
        (<>
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e052.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e052an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e052.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 6 0)
         (animate 1 6)
         (delay)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e053.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e053an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e053.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 6 0)
         (animate 1 6)
         (delay)))
      (if (== (: 374) 1)
        (<>
         (slot 1 3)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e054.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e054an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e054.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 6 0)
         (animate 1 6)
         (delay)))
      (if (== (: 375) 1)
        (<>
         (slot 1 3)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e055.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e055an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e055.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 6 0)
         (animate 1 6)
         (delay)))
      (if (== (: 324) 1)
        (<>
         (slot 1 4)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e045.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e045an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e045.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 6 0)
         (animate 1 6)
         (delay)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e046.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e046an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e046.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 6 0)
         (animate 1 6)
         (delay)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e047.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e047an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e047.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 6 0)
         (animate 1 6)
         (delay)))
      (if (== (: 261) 1)
        (<>
         (slot 1 4)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e026.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e026an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e026.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 3 0)
         (animate 1 3)
         (delay)))
      (if (== (: 262) 1)
        (<>
         (slot 1 4)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e027.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e027an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e027.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 3 0)
         (animate 1 3)
         (delay)))
      (if (== (: 263) 1)
        (<>
         (slot 1 4)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e028.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e028an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e028.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 3 0)
         (animate 1 3)
         (delay)))
      (if (== (: 264) 1)
        (<>
         (slot 1 4)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e029.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e029an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e029.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 3 0)
         (animate 1 3)
         (delay)))
      (if (== (: 265) 1)
        (<>
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e030.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e030an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e030.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 3 0)
         (animate 1 3)
         (delay)))
      (if (== (: 257) 1)
        (<>
         (slot 1 4)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e039.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e039an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e039.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 3 0)
         (animate 1 3)
         (animate 0 6 1)
         (animate 1 6)
         (delay)))
      (if (== (: 257) 1)
        (<>
         (slot 1 4)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e031.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e031an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e031.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 3 0)
         (animate 1 3)
         (delay)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e032.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e032an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e032.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 3 0)
         (animate 1 3)
         (delay)))
      (if (== (: 306) 1)
        (<>
         (slot 1 4)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e035.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e035an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e035.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 6 0)
         (animate 1 6)
         (animate 0 0 1)
         (animate 1 0)
         (delay)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e036.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e036an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e036.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 6 0)
         (animate 1 6)
         (delay)))
      (if (== (: 302) 1)
        (<>
         (slot 1 4)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e033.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e033an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e033.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 3 0)
         (animate 1 3)
         (delay)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e034.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e034an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e034.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 3 0)
         (animate 1 3)
         (delay)))
      (if (== (: 309) 1)
        (<>
         (slot 1 4)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e037.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e037an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e037.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 3 0)
         (animate 1 3)
         (delay)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e038.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e038an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e038.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 3 0)
         (animate 1 3)
         (delay)))
      (if (== (: 413) 1)
        (<>
         (slot 1 4)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e007.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e007an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e007.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 3 0)
         (animate 1 3)
         (delay)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e008.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e008an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e008.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 3 0)
         (animate 1 3)
         (animate 0 0 1)
         (animate 1 0)
         (delay)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e009.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e009an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e009.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 3 0)
         (animate 1 3)
         (animate 0 0 1)
         (animate 1 0)
         (delay)))
      (if (== (: 217) 1)
        (<>
         (slot 1 5)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e023.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e023an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e023.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 3 0)
         (animate 1 3)
         (delay)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e024.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e024an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e024.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 3 0)
         (animate 1 3)
         (delay)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e025.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e025an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e025.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 3 0)
         (animate 1 3)
         (delay)))
      (if (== (: 467) 1)
        (<>
         (slot 1 5)
         (proc 3)
         (set-arr~ @ 12 2)
         (image "e072.pd8")
         (proc 4)
         (proc 6)
         (set-arr~ @ 12 2)
         (image "e072an.pd8")
         (proc 7)
         (set-arr~ @ 7 0)
         (set-arr~ @ 2 40960)
         (load "e072.s4" (~ @ 2))
         (set-arr~ @ 7 1)
         (animate 0 6 0)
         (animate 1 6)
         (delay)))))
    ((== S 2)
     (<>
      (palette 3 0)
      (set-arr~ @ 13 0 0 79 399)
      (color 8)
      (clear)
      (set-arr~ @ 17 0 150)
      (text "　　　　　　　　　< Dragon Knight III Music Mode >")
      (set-arr~ @ 13 0 180 79 250)
      (color 8)
      (clear)
      (text-color 6)
      (palette 3)
      (set-arr~ @ 7 0)
      (set-arr~ @ 3 49152)
      (text "　　　　　　　　　　　　　　　< Opening >")
      (load "OPEN2_2.M" (~ @ 3))
      (sound 1)
      (sound 0)
      (delay)
      (clear)
      (text "　　　　　　　　　　　　　　　　< Title >")
      (load "OSOWALER.M" (~ @ 3))
      (sound 1)
      (sound 0)
      (delay)
      (clear)
      (text "　　　　　　　　　　　　　　　<　Town of Deese　>")
      (load "HEYGEN1.M" (~ @ 3))
      (sound 1)
      (sound 0)
      (delay)
      (clear)
      (text "　　　　　　　　　　　　　　< Nudist Village >")
      (load "RESORT.M" (~ @ 3))
      (sound 1)
      (sound 0)
      (delay)
      (clear)
      (text "　　　　　　　　　　　　　　　<　Town of Tyson　>")
      (load "HEYGEN2.M" (~ @ 3))
      (sound 1)
      (sound 0)
      (delay)
      (clear)
      (text "　　　　　　　　　　　　　<　Strawberry Fields　>")
      (load "OPEN.M" (~ @ 3))
      (sound 1)
      (sound 0)
      (delay)
      (clear)
      (text "　　　　　　　　　　　　　　　<　Little Red Riding Hood's House　>")
      (load "DISNEY.M" (~ @ 3))
      (sound 1)
      (sound 0)
      (delay)
      (clear)
      (text "　　　　　　　　　　　　　　　　<　Fairy Village　>")
      (load "KOBITO2.M" (~ @ 3))
      (sound 1)
      (sound 0)
      (delay)
      (clear)
      (text "　　　　　　　　　　　　　　　　<　Cat Tribe Village　>")
      (load "NEKO.M" (~ @ 3))
      (sound 1)
      (sound 0)
      (delay)
      (clear)
      (text "　　　　　　　　　　　　　　　<　Field 1　>")
      (load "FIELD.M" (~ @ 3))
      (sound 1)
      (sound 0)
      (delay)
      (clear)
      (text "　　　　　　　　　　　　　　　<　Field 2　>")
      (load "OPEN2.M" (~ @ 3))
      (sound 1)
      (sound 0)
      (delay)
      (clear)
      (text "　　　　　　　　　　　　　　　< Rimtoss Mountain >")
      (load "DANGYON.M" (~ @ 3))
      (sound 1)
      (sound 0)
      (delay)
      (clear)
      (text "　　　　　　　　　　　　　　　　　＜　Graveyard　＞")
      (load "TOWER.M" (~ @ 3))
      (sound 1)
      (sound 0)
      (delay)
      (clear)
      (text "　　　　　　　　　　　　　　　<　Callisto's Castle　>")
      (load "DUNGEON2.M" (~ @ 3))
      (sound 1)
      (sound 0)
      (delay)
      (clear)
      (text "　　　　　　　　　　　　　　　<　Dog Tribe Cave　>")
      (load "INU.M" (~ @ 3))
      (sound 1)
      (sound 0)
      (delay)
      (clear)
      (text "　　　　　　　　　　　　　　　<　Temple of the Messiah　>")
      (load "KANASII.M" (~ @ 3))
      (sound 1)
      (sound 0)
      (delay)
      (clear)
      (text "　　　　　　　　　　　　　　　<　Final Cave　>")
      (load "DOUKUTU.M" (~ @ 3))
      (sound 1)
      (sound 0)
      (delay)
      (clear)
      (text "　　　　　　　　　　　　　　<　Monster Battle 1　>")
      (load "GENSTER.M" (~ @ 3))
      (sound 1)
      (sound 0)
      (delay)
      (clear)
      (text "　　　　　　　　　　　　　　<　Monster Battle 2　>")
      (load "GANSTER.M" (~ @ 3))
      (sound 1)
      (sound 0)
      (delay)
      (clear)
      (text "　　　　　　　　　　　　　　<　Monster Battle 3　>")
      (load "MORISTER.M" (~ @ 3))
      (sound 1)
      (sound 0)
      (delay)
      (clear)
      (text "　　　　　　　　　　　　　<　Boss Monster Battle　>")
      (load "BOSS3.M" (~ @ 3))
      (sound 1)
      (sound 0)
      (delay)
      (clear)
      (text "　　　　　　　　　　　　　　　<　Deed Battle　>")
      (load "OBOSTER.M" (~ @ 3))
      (sound 1)
      (sound 0)
      (delay)
      (clear)
      (text "　　　　　　　　　　　　　　<　Scene 1　>")
      (load "H.M" (~ @ 3))
      (sound 1)
      (sound 0)
      (delay)
      (clear)
      (text "　　　　　　　　　　　　　　<　Scene 2　>")
      (load "H2.M" (~ @ 3))
      (sound 1)
      (sound 0)
      (delay)
      (clear)
      (text "　　　　　　　　　　　　　　　　　< Inn >")
      (load "YADOYA.M" (~ @ 3))
      (sound 1)
      (sound 0)
      (delay)
      (clear)
      (text "　　　　　　　　　　　　　　　　<　Secondhand Store　>")
      (load "DOUGUYA.M" (~ @ 3))
      (sound 1)
      (sound 0)
      (delay)
      (clear)
      (text "　　　　　　　　　　　　　　　　<　Weapons Dealer　>")
      (load "BUKIYA.M" (~ @ 3))
      (sound 1)
      (sound 0)
      (delay)
      (clear)
      (text "　　　　　　　　　　　　　　<　Game Over　>")
      (load "OWARI.M" (~ @ 3))
      (sound 1)
      (sound 0)
      (delay)
      (clear)
      (text "　　　　　　　　　　　　　　　　<　Goddess' Entrance　>")
      (load "MESIA.M" (~ @ 3))
      (sound 1)
      (sound 0)
      (delay)
      (clear)
      (text "　　　　　　　　　　　　　　　　<　Triumphant Return　>")
      (load "GAISENN.M" (~ @ 3))
      (sound 1)
      (sound 0)
      (delay)
      (clear)
      (sound 1)))
    ((== S 3)
     (<>
      (set-var I 0)
      (while (!= I 1024) (<> (set-reg:: I 0) (set-var I (+ I 1))))
      (mes-jump "open.mes")))))))