(mes
 (meta (engine 'AI5) (charset "pc98") (dictbase 128))
 (dict
  #\【
  #\】
  #\。
  #\い
  #\、
  #\な
  #\…
  #\の
  #\だ
  #\ん
  #\て
  #\る
  #\っ
  #\か
  #\に
  #\う
  #\は
  #\が
  #\た
  #\あ
  #\よ
  #\み
  #\し
  #\こ
  #\ら
  #\ず
  #\も
  #\？
  #\れ
  #\と
  #\を
  #\u3000
  #\で
  #\ゃ
  #\ち
  #\部
  #\そ
  #\く
  #\け
  #\き
  #\り
  #\つ
  #\弓
  #\道
  #\す
  #\え
  #\ま
  #\ど
  #\わ
  #\練
  #\習
  #\唯
  #\じ
  #\さ
  #\ー
  #\子
  #\ろ
  #\事
  #\お
  #\場
  #\や
  #\ぞ
  #\生
  #\洋
  #\俺
  #\め
  #\学
  #\！
  #\（
  #\）
  #\へ
  #\何
  #\ね
  #\気
  #\行
  #\ふ
  #\バ
  #\話
  #\校
  #\見
  #\間
  #\先
  #\言
  #\的
  #\イ
  #\ク
  #\日
  #\根
  #\来
  #\ば
  #\屋
  #\ン
  #\ッ
  #\人
  #\片
  #\桐
  #\中
  #\リ
  #\ス
  #\今
  #\ほ
  #\天
  #\野
  #\入
  #\せ
  #\思
  #\兄
  #\女
  #\時
  #\一
  #\八
  #\体
  #\柱
  #\聞
  #\ラ
  #\違
  #\込
  #\ぶ
  #\ト
  #\誰
  #\立
  #\照
  #\明
  #\ド
  #\植
  #\空
  #\面
  #\引)
 (define-proc 11
   (<>
    (color 192)
    (box 68 358 78 388)
    (if-else (== M 0)
      (<> (blit 0 152 1 183 3 77 357 0) (blit 20 152 20 183 3 76 357 0))
      (<>
       (set-var I M)
       (set-var J 0)
       (while
        (!= J 6)
        (<>
         (if-else (== I 0)
           (<> (blit 20 152 20 183 3 (+ (- 77 (* J 2)) 1) 357 0) (break))
           (<>
            (blit
             (* (% I 10) 2)
             152
             (+ (* (% I 10) 2) 1)
             183
             3
             (- 77 (* J 2))
             357
             0)
            (set-var I (/ I 10))))
         (set-var J (+ J 1))))))
    (set-var I (/ H 100))
    (if (> I 12) (<> (set-var I (- I 12))))
    (blit (* (/ I 10) 2) 184 (+ (* (/ I 10) 2) 1) 199 3 18 295 0)
    (blit (* (% I 10) 2) 184 (+ (* (% I 10) 2) 1) 199 3 20 295 0)
    (blit 20 184 21 199 3 22 295 0)
    (blit
     (* (/ (% H 100) 10) 2)
     184
     (+ (* (/ (% H 100) 10) 2) 1)
     199
     3
     24
     295
     0)
    (blit
     (* (% (% H 100) 10) 2)
     184
     (+ (* (% (% H 100) 10) 2) 1)
     199
     3
     26
     295
     0)
    (blit 22 184 23 199 3 28 295 0)
    (blit 0 (* E 16) 12 (+ (* E 16) 15) 3 49 295 0)
    (set-var I (% (/ T 100) 12))
    (if (&& (== (/ T 100 12) 1) (== I 0)) (<> (set-var I 12)))
    (if-else (== (/ I 10) 0)
      (<> (color 192) (box 71 319 71 348))
      (<> (blit 3 153 3 182 3 71 319 0)))
    (blit (* (% I 10) 2) 152 (+ (* (% I 10) 2) 1) 183 3 72 318 0)
    (blit 21 (+ 152 1) 21 (- 183 1) 3 74 319 0)
    (set-var I (% T 100))
    (blit (* (/ I 10) 2) 152 (+ (* (/ I 10) 2) 1) 183 3 75 318 0)
    (blit (* (% I 10) 2) 152 (+ (* (% I 10) 2) 1) 183 3 77 318 0)
    (set-var I (/ T 100 12))
    (blit (+ 22 (* I 2)) 152 (+ 23 (* I 2)) 183 3 68 318 0)
    (color 7)))
 (define-proc 13
   (<>
    (set-var I (+ (% T 100) A))
    (set-var T (/ T 100))
    (set-var T (+ T (/ I 60)))
    (set-var I (% I 60))
    (set-var T (+ (* T 100) I))
    (if (> (/ T 100) 23)
      (<>
       (if-else (== (/ H 100) 11) (<> (set-var J 31)) (<> (set-var J 32)))
       (set-var E (+ E (/ T 100 24)))
       (if (> E 6) (<> (set-var E (% E 7))))
       (set-var I (+ (% H 100) (/ T 100 24)))
       (set-var H (/ H 100))
       (set-var H (+ (* (+ H (/ I J)) 100) (% I J)))
       (set-var T (+ (% T 100) (* (% (/ T 100) 24) 100)))
       (if (== H 1300) (<> (set-var H 1301)))
       (proc 3)))))
 (define-proc 3
   (<>
    (if (== (: 628) 1) (<> (set-reg: 628 0)))
    (if (== (: 651) 1) (<> (set-reg: 651 0)))
    (if (== (: 652) 1) (<> (set-reg: 652 0)))
    (if (== (: 707) 1) (<> (set-reg: 707 0)))
    (if (== (: 718) 1) (<> (set-reg: 718 0)))
    (if (== (: 813) 1) (<> (set-reg: 813 0)))
    (if (== (: 815) 1) (<> (set-reg: 815 0)))
    (cond
     ((== (: 810) 1) (<> (set-reg: 810 0)))
     ((== (: 810) 0) (<> (set-reg: 810 1))))
    (if (== H 1231) (<> (set-reg: 810 2)))
    (if (== (: 914) 1) (<> (set-reg: 914 0)))
    (cond
     ((== (: 910) 1) (<> (set-reg: 910 0)))
     ((== (: 910) 0) (<> (set-reg: 910 1))))
    (if (&& (> H 1227) (!= (: 910) 3)) (<> (set-reg: 910 2)))
    (if (== (: 1068) 1) (<> (set-reg: 1068 0)))
    (if (== (: 1069) 1) (<> (set-reg: 1069 0)))
    (cond
     ((== (: 1173) 1) (<> (set-reg: 1173 0)))
     ((== (: 1173) 0) (<> (set-reg: 1173 1))))
    (if (== (: 1179) 1) (<> (set-reg: 1179 0)))
    (if (== (: 1180) 1) (<> (set-reg: 1180 0)))
    (if-else (// (== H 1224) (== H 1301))
      (<> (set-reg: 1375 1))
      (<> (set-reg: 1375 0)))
    (if-else (== H 1301) (<> (set-reg: 1419 1)) (<> (set-reg: 1419 0)))
    (if (== (: 1440) 1) (<> (set-reg: 1440 0)))
    (if (== (: 1471) 1) (<> (set-reg: 1471 0)))
    (if (&& (== (: 1470) 1) (== (: 1472) 0)) (<> (set-reg: 1375 1)))
    (if (&& (== (: 1077) 1) (== (: 1082) 0) (== (: 1416) 0))
      (<> (set-reg: 1375 1)))
    (if (== (: 1082) 1) (<> (set-reg: 1375 1)))
    (if (== (: 1481) 1) (<> (set-reg: 1375 1)))
    (if (== (: 1439) 1) (<> (set-reg: 1419 1)))
    (if (== (: 1541) 1) (<> (set-reg: 1541 0)))
    (if (== (: 1600) 1) (<> (set-reg: 1600 0)))
    (if (== H 1224) (<> (set-reg: 1598 1)))
    (if (== H 1301) (<> (set-reg: 1598 1)))
    (if (== (: 1810) 1) (<> (set-reg: 1810 0)))))
 (define-proc 14
   (<>
    (set-var I (% T 100))
    (set-var T (+ (/ T 100) A))
    (set-var T (+ T (/ I 60)))
    (set-var I (% I 60))
    (set-var T (+ (* T 100) I))
    (if (> (/ T 100) 23)
      (<>
       (if-else (== (/ H 100) 11) (<> (set-var J 31)) (<> (set-var J 32)))
       (set-var E (+ E (/ T 100 24)))
       (if (> E 6) (<> (set-var E (% E 7))))
       (set-var I (+ (% H 100) (/ T 100 24)))
       (set-var H (/ H 100))
       (set-var H (+ (* (+ H (/ I J)) 100) (% I J)))
       (set-var T (+ (% T 100) (* (% (/ T 100) 24) 100)))))))
 (define-proc 15
   (<>
    (if (== (: 2024) 0)
      (<>
       (set-var I T)
       (cond
        ((< I 530) (<> (set-var J 34304)))
        ((< I 630) (<> (set-var J 33792)))
        ((< I 1600) (<> (set-reg: 191 1)))
        ((< I 1730) (<> (set-var J 34560)))
        (else (<> (set-var J 34304))))
       (if (== (: 191) 0)
         (<>
          (set-var I 8)
          (while
           (!= I 11)
           (<> (set-arr~ @ (+ 31 I) (~ J I)) (set-var I (+ I 1))))))))
    (set-reg: 191 0)))
 (define-proc 16
   (<>
    (set-var I 0)
    (while
     (!= I (/ (~ @ 97) 2))
     (<>
      (blit
       (~ @ 94)
       (+ (~ @ 95) (* I 2))
       (- (+ (~ @ 94) (~ @ 96)) 1)
       (+ (~ @ 95) (* I 2))
       1
       (~ @ 94)
       (+ (~ @ 95) (* I 2))
       0)
      (blit
       (~ @ 94)
       (- (+ (~ @ 95) (* (/ (~ @ 97) 2) 2)) 1 (* I 2))
       (- (+ (~ @ 94) (~ @ 96)) 1)
       (- (+ (~ @ 95) (* (/ (~ @ 97) 2) 2)) 1 (* I 2))
       1
       (~ @ 94)
       (- (+ (~ @ 95) (* (/ (~ @ 97) 2) 2)) 1 (* I 2))
       0)
      (set-var I (+ I 1))))
    (if (== (&& (~ @ 97) 1) 1)
      (<>
       (blit
        (~ @ 94)
        (- (+ (~ @ 95) (~ @ 97)) 1)
        (- (+ (~ @ 94) (~ @ 96)) 1)
        (- (+ (~ @ 95) (~ @ 97)) 1)
        1
        (~ @ 94)
        (- (+ (~ @ 95) (~ @ 97)) 1)
        0)))
    (set-arr~ @ 6 0)))
 (define-proc 17
   (<>
    (set-var I 0)
    (while
     (!= I (/ (~ @ 97) 2))
     (<>
      (blit-mask
       (~ @ 94)
       (+ (~ @ 95) (* I 2))
       (- (+ (~ @ 94) (~ @ 96)) 1)
       (+ (~ @ 95) (* I 2))
       1
       (~ @ 94)
       (+ (~ @ 95) (* I 2))
       0)
      (blit-mask
       (~ @ 94)
       (- (+ (~ @ 95) (* (/ (~ @ 97) 2) 2)) 1 (* I 2))
       (- (+ (~ @ 94) (~ @ 96)) 1)
       (- (+ (~ @ 95) (* (/ (~ @ 97) 2) 2)) 1 (* I 2))
       1
       (~ @ 94)
       (- (+ (~ @ 95) (* (/ (~ @ 97) 2) 2)) 1 (* I 2))
       0)
      (set-var I (+ I 1))))
    (if (== (&& (~ @ 97) 1) 1)
      (<>
       (blit-mask
        (~ @ 94)
        (- (+ (~ @ 95) (~ @ 97)) 1)
        (- (+ (~ @ 94) (~ @ 96)) 1)
        (- (+ (~ @ 95) (~ @ 97)) 1)
        1
        (~ @ 94)
        (- (+ (~ @ 95) (~ @ 97)) 1)
        0)))
    (set-arr~ @ 6 0)))
 (define-proc 19
   (<>
    (blit-mask
     (~ @ 94)
     (~ @ 95)
     (- (+ (~ @ 94) (~ @ 96)) 1)
     (- (+ (~ @ 95) (~ @ 97)) 1)
     2
     (~ @ 94)
     (~ @ 95)
     1)))
 (define-proc 20
   (<>
    (define-proc 30
      (<>
       (if (!= (~ @ 23) 65535)
         (<>
          (set-arr~ @ 6 0)
          (color 112)
          (box-inv
           (+ X 1)
           (+ Y 10 (* (~ @ 23) 18))
           (+ X 20)
           (+ Y 10 (* (~ @ 23) 18) 15))
          (set-var N (~ @ 23))
          (color 7)))))
    (define-proc 31
      (<>
       (menu-init 0)
       (if-else (> (~ @ 24) 0)
         (<> (blit 13 36 34 45 3 X Y 0))
         (<> (blit 13 0 34 9 3 X Y 0)))
       (set-var L (- (~ @ 26) (~ @ 24)))
       (if (> L 10) (<> (set-var L 10)))
       (set-var I 0)
       (while
        (< I L)
        (<> (blit 13 10 34 27 3 X (+ Y 10 (* I 18)) 0) (set-var I (+ I 1))))
       (if-else (> (- (~ @ 26) (~ @ 24)) 10)
         (<> (blit 13 46 34 53 3 X (+ Y 10 (* L 18)) 0))
         (<> (blit 13 28 34 35 3 X (+ Y 10 (* L 18)) 0)))
       (set-var J (~ @ 22))
       (color 7)
       (set-arr~ @ 6 0)
       (set-var I 0)
       (while
        (< I L)
        (<>
         (set-arr~ @ 17 (+ X 1) (+ Y 10 (* I 18)))
         (call (~ J (* I 2)))
         (set-var I (+ I 1))))))
    (define-proc 32
      (<>
       (mouse 2)
       (if (&& (> (~ @ 10) (+ (* X 8) 7)) (< (~ @ 10) (+ (* X 8) 168)))
         (<>
          (cond
           ((&& (> (~ @ 11) (+ Y 10)) (< (~ @ 11) (+ Y (* L 18) 1)))
            (<>
             (set-var J (~ @ 22))
             (set-var N (~ J (+ (* (~ @ 23) 2) 1)))
             (mouse 1)
             (set-arr~ @ 27 0)
             (blit 0 200 21 399 3 X Y 0)
             (set-arr~ @ 7 (~ @ 49))
             (if-else (== (: 2027) 0) (<> (proc 23)) (<> (set-reg: 2027 0)))
             (set-arr~ @ 9 (&& (~ @ 9) 65533))
             (set-reg: 2023 0)))
           ((&&
             (// (== (~ @ 11) Y) (> (~ @ 11) Y))
             (< (~ @ 11) (+ Y 10))
             (> (~ @ 24) 0))
            (<>
             (mouse 1)
             (blit 0 200 21 399 3 X Y 0)
             (set-arr~ @ 24 (- (~ @ 24) 10))
             (proc 31)
             (set-arr~ @ 23 65535)
             (proc 30)
             (mouse 0)))
           ((&&
             (> (~ @ 11) (+ (+ Y (* L 18)) 10))
             (< (~ @ 11) (+ Y (* L 18) 24))
             (> (~ @ 26) (+ (~ @ 24) 10)))
            (<>
             (mouse 1)
             (blit 0 200 21 399 3 X Y 0)
             (set-arr~ @ 24 (+ (~ @ 24) 10))
             (proc 31)
             (set-arr~ @ 23 65535)
             (proc 30)
             (mouse 0))))))))
    (define-proc 33
      (<>
       (if (== (: 2023) 0)
         (<>
          (set-var N 0)
          (mouse 1)
          (set-arr~ @ 27 0)
          (blit 0 200 21 399 3 X Y 0)
          (set-arr~ @ 7 (~ @ 49))
          (if-else (== (: 2027) 0) (<> (proc 23)) (<> (set-reg: 2027 0)))
          (set-arr~ @ 9 (&& (~ @ 9) 65533))))))
    (define-proc 34
      (<>
       (cond
        ((== (~ @ 23) 65535)
         (<>
          (mouse 1)
          (set-arr~ @ 23 N)
          (proc 30)
          (mouse 3 (+ (* X 8) 160) (+ Y 14 (* (~ @ 23) 18)))
          (mouse 0)))
        ((!= (~ @ 23) 0)
         (<>
          (mouse 1)
          (proc 30)
          (set-arr~ @ 23 (- (~ @ 23) 1))
          (proc 30)
          (mouse 3 (+ (* X 8) 160) (+ Y 14 (* (~ @ 23) 18)))
          (mouse 0)))
        (else
         (<>
          (if (!= (~ @ 24) 0)
            (<>
             (mouse 1)
             (blit 0 200 21 399 3 X Y 0)
             (set-arr~ @ 24 (- (~ @ 24) 10))
             (set-arr~ @ 23 9)
             (proc 31)
             (proc 30)
             (mouse 3 (+ (* X 8) 160) (+ Y 14 (* (~ @ 23) 18)))
             (mouse 0))))))))
    (define-proc 35
      (<>
       (cond
        ((== (~ @ 23) 65535)
         (<>
          (mouse 1)
          (set-arr~ @ 23 N)
          (proc 30)
          (mouse 3 (+ (* X 8) 160) (+ Y 14 (* (~ @ 23) 18)))
          (mouse 0)))
        ((< (~ @ 23) (- L 1))
         (<>
          (mouse 1)
          (proc 30)
          (set-arr~ @ 23 (+ (~ @ 23) 1))
          (proc 30)
          (mouse 3 (+ (* X 8) 160) (+ Y 14 (* (~ @ 23) 18)))
          (mouse 0)))
        (else
         (<>
          (if (> (~ @ 26) (+ (~ @ 24) 10))
            (<>
             (mouse 1)
             (blit 0 200 21 399 3 X Y 0)
             (set-arr~ @ 24 (+ (~ @ 24) 10))
             (set-arr~ @ 23 0)
             (proc 31)
             (proc 30)
             (mouse 3 (+ (* X 8) 160) (+ Y 14 (* (~ @ 23) 18)))
             (mouse 0))))))))
    (define-proc 36 (<>))
    (define-proc 37 (<>))
    (define-proc 38
      (<>
       (set-arr~ @ 9 (// (~ @ 9) 2))
       (set-var X (+ (* (: 1001) 38) 10))
       (set-var Y 0)
       (set-arr~ @ 49 (~ @ 7))
       (set-arr~ @ 7 0)
       (blit X Y (+ X 22) (+ Y 199) 0 0 200 3)
       (set-arr~ @ 23 0)
       (set-arr~ @ 24 0)
       (set-arr~ @ 25 10)
       (mouse 1)
       (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
       (set-arr~ @ 21 (+ 512 16))
       (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
       (set-arr~ @ 13 0 0 79 399)
       (menu-init 1)
       (proc 31)
       (proc 30)
       (set-arr~ @ 48 (~ @ 7))
       (set-arr~ @ 7 1)
       (mouse 4 36864)
       (set-arr~ @ 7 (~ @ 48))
       (mouse 3 (+ (* X 8) 160) (+ Y 14 (* (~ @ 23) 18)))
       (mouse 0)))
    (define-proc 39
      (<>
       (mouse 2)
       (if-else (&&
                 (> (~ @ 10) (+ (* X 8) 7))
                 (< (~ @ 10) (+ (* X 8) 168))
                 (> (~ @ 11) (+ Y 10))
                 (< (~ @ 11) (+ Y (* L 18) 1)))
         (<>
          (set-var I (/ (- (~ @ 11) Y 8) 18))
          (if (!= (~ @ 23) I)
            (<> (mouse 1) (proc 30) (set-arr~ @ 23 I) (proc 30) (mouse 0))))
         (<>
          (if (!= (~ @ 23) 65535)
            (<> (mouse 1) (proc 30) (set-arr~ @ 23 65535) (mouse 0)))))))))
 (define-proc 21
   (<>
    (set-arr~ @ 7 0)
    (define-proc 30 (<>))
    (define-proc 31 (<>))
    (define-proc 32
      (<>
       (mouse 2)
       (set-var X (+ (~ @ 10) 8))
       (set-var Y (+ (~ @ 11) 8))
       (mouse 1)
       (if (!= (~ @ 23) 65535)
         (<>
          (set-arr~ @ 27 0)
          (set-var N (&& (~ @ 23) 255))
          (set-var V (+ (/ (~ @ 23) 256) 1))))
       (set-arr~ @ 23 65280)
       (if (== (: 2000) 0)
         (<>
          (set-arr~ @ 13 33 295 46 311)
          (color 7)
          (clear)
          (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
          (set-arr~ @ 21 (+ 512 16))
          (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
          (set-arr~ @ 20 (&& (~ @ 20) 4095))
          (color 7)
          (set-arr~ @ 6 0)
          (set-arr~ @ 13 15 328 64 387)
          (clear)
          (color 7)))
       (if-else (== (~ @ 27) 0)
         (<>
          (set-arr~ @ 48 (~ @ 7))
          (set-arr~ @ 7 1)
          (mouse 4 36864)
          (set-arr~ @ 7 (~ @ 48))
          (set-reg: 2000 0))
         (<> (mouse 0)))))
    (define-proc 33
      (<>
       (if (== (: 2000) 0)
         (<>
          (mouse 1)
          (set-arr~ @ 27 0)
          (set-arr~ @ 23 0)
          (set-var V 0)
          (set-var N 0)
          (set-arr~ @ 23 65280)
          (set-arr~ @ 13 33 295 46 311)
          (color 7)
          (clear)
          (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
          (set-arr~ @ 21 (+ 512 16))
          (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
          (set-arr~ @ 20 (&& (~ @ 20) 4095))
          (color 7)
          (set-arr~ @ 6 0)
          (set-arr~ @ 13 15 328 64 387)
          (clear)
          (color 7)
          (set-arr~ @ 48 (~ @ 7))
          (set-arr~ @ 7 1)
          (mouse 4 36864)
          (set-arr~ @ 7 (~ @ 48))))))
    (define-proc 34 (<>))
    (define-proc 35 (<>))
    (define-proc 36 (<>))
    (define-proc 37 (<>))
    (define-proc 38
      (<>
       (mouse 1)
       (if (== (: 2000) 0)
         (<>
          (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
          (set-arr~ @ 21 (+ 512 16))
          (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
          (set-arr~ @ 20 (&& (~ @ 20) 4095))
          (color 7)
          (set-arr~ @ 6 0)
          (set-arr~ @ 13 15 328 64 387)
          (clear)
          (color 7)
          (text "アイコンで画面をクリックしてください。")
          (set-arr~ @ 13 33 295 46 311)
          (color 7)
          (clear)))
       (set-arr~ @ 23 65280)
       (set-arr~ @ 48 (~ @ 7))
       (set-arr~ @ 7 1)
       (mouse 4 36864)
       (set-arr~ @ 7 (~ @ 48))
       (mouse 0)))
    (define-proc 39
      (<>
       (mouse 2)
       (set-var X (+ (~ @ 10) 8))
       (set-var Y (+ (~ @ 11) 8))
       (set-arr~ @ 48 (~ @ 7))
       (set-arr~ @ 7 1)
       (click 34816 X Y)
       (set-var J S)
       (set-arr~ @ 7 (~ @ 48))
       (if (!= (~ @ 23) J)
         (<>
          (set-arr~ @ 23 J)
          (mouse 1)
          (set-arr~ @ 17 33 295)
          (color 7)
          (set-var I (+ (/ (~ @ 23) 256) 1))
          (set-arr~ @ 48 (~ @ 7))
          (set-arr~ @ 7 1)
          (if-else (> I 13)
            (<> (mouse 4 36864))
            (<> (mouse 4 (+ 36864 (* 512 I)))))
          (set-arr~ @ 7 (~ @ 48))
          (if (== (: 2000) 0)
            (<>
             (cond
              ((== I 1)
               (<>
                (set-arr~ @ 21 (+ 256 16))
                (str " ")
                (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
                (set-arr~ @ 21 (+ 512 16))
                (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
                (text "見る・調べる")
                (set-arr~ @ 21 (+ 256 16))
                (str " ")))
              ((== I 2) (<> (text "　　はなす　　")))
              ((== I 3) (<> (text "　殴る・叩く　")))
              ((== I 4) (<> (text "　押す・引く　")))
              ((== I 5) (<> (text "　　あける　　")))
              ((== I 6)
               (<>
                (text "　　")
                (set-arr~ @ 21 (+ 256 16))
                (str " ")
                (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
                (set-arr~ @ 21 (+ 512 16))
                (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
                (text "取る　　")
                (set-arr~ @ 21 (+ 256 16))
                (str " ")))
              ((== I 7)
               (<>
                (text "　")
                (set-arr~ @ 21 (+ 256 16))
                (str " ")
                (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
                (set-arr~ @ 21 (+ 512 16))
                (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
                (text "キスする　")
                (set-arr~ @ 21 (+ 256 16))
                (str " ")))
              ((== I 8) (<> (text "　　さわる　　")))
              ((== I 9)
               (<>
                (text "　　")
                (set-arr~ @ 21 (+ 256 16))
                (str " ")
                (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
                (set-arr~ @ 21 (+ 512 16))
                (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
                (text "もむ　　")
                (set-arr~ @ 21 (+ 256 16))
                (str " ")))
              ((== I 10) (<> (text "　　なめる　　")))
              ((== I 11)
               (<>
                (text "　　")
                (set-arr~ @ 21 (+ 256 16))
                (str " ")
                (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
                (set-arr~ @ 21 (+ 512 16))
                (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
                (text "かむ　　")
                (set-arr~ @ 21 (+ 256 16))
                (str " ")))
              ((== I 12) (<> (text "　×××する　")))
              ((== I 13) (<> (text "　　？？？　　")))
              (else (<> (text "　　　　　　　"))))
             (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
             (set-arr~ @ 21 (+ 512 16))
             (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))))
          (mouse 0)))))))
 (define-proc 23
   (<>
    (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
    (set-arr~ @ 21 (+ 512 16))
    (set-arr~ @ 21 531)
    (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
    (set-arr~ @ 20 (&& (~ @ 20) 4095))
    (color 7)
    (set-arr~ @ 6 0)
    (set-arr~ @ 13 15 328 64 387)
    (clear)))
 (define-proc 10
   (<>
    (if (== (: 2022) 1)
      (<>
       (blit 0 316 65 399 1 7 300 0)
       (if (== (: 2025) 1) (<> (set-arr~ @ 9 (&& (~ @ 9) 65533))))
       (set-reg: 2022 0)))))
 (define-proc 56
   (<>
    (if (== (: 2022) 0)
      (<>
       (set-reg: 2022 1)
       (if (== (: 2025) 1) (<> (set-arr~ @ 9 (// (~ @ 9) 2))))
       (blit 7 300 72 383 0 0 316 1)
       (blit 26 116 26 199 3 0 316 3)
       (blit 27 116 28 199 3 1 316 3)
       (blit 27 116 28 199 3 3 316 3)
       (blit 1 316 4 399 3 5 316 3)
       (blit 1 316 8 399 3 9 316 3)
       (blit 1 316 16 399 3 17 316 3)
       (blit 1 316 32 399 3 33 316 3)
       (blit 29 116 29 199 3 65 316 3)
       (blit 0 316 65 399 3 7 300 0)
       (set-arr~ @ 13 9 312 70 368)
       (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
       (set-arr~ @ 21 (+ 512 16))
       (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
       (set-arr~ @ 21 531)
       (color 7)
       (set-arr~ @ 6 0)
       (clear)))))
 (define-proc 57
   (<>
    (define-proc 30 (<>))
    (define-proc 31 (<>))
    (define-proc 32
      (<> (if-else (== I 0) (<> (set-arr~ @ 27 0)) (<> (proc 33)))))
    (define-proc 33
      (<>
       (if-else (== I 0)
         (<>
          (blit 7 300 72 383 0 0 316 3)
          (blit 0 316 65 399 1 7 300 0)
          (set-var I 1))
         (<> (blit 0 316 65 399 3 7 300 0) (set-var I 0)))))
    (define-proc 34 (<>))
    (define-proc 35 (<>))
    (define-proc 36 (<>))
    (define-proc 37 (<>))
    (define-proc 38 (<>))
    (define-proc 39 (<>))
    (set-var I 0)
    (set-arr~ @ 51 (~ @ 7))
    (set-arr~ @ 7 0)
    (menu-show (<> (text "あ")))
    (set-arr~ @ 7 (~ @ 51))
    (clear)))
 (define-proc 58
   (<>
    (set-arr~ @ 49 X)
    (set-arr~ @ 50 Y)
    (set-arr~ @ 51 (~ @ 7))
    (set-arr~ @ 7 0)
    (set-var X (~ @ 0))))
 (define-proc 59
   (<> (set-var X (~ @ 49)) (set-var Y (~ @ 50)) (set-arr~ @ 7 (~ @ 51))))
 (define-proc 22
   (<>
    (util 2 0 0)
    (set-var I 0)
    (while
     (!= I 144)
     (<>
      (blit 8 (* I 2) 71 (* I 2) 1 8 (* I 2) 0)
      (blit 8 (- 287 (* I 2)) 71 (- 287 (* I 2)) 1 8 (- 287 (* I 2)) 0)
      (set-var I (+ I 1))))
    (util 2 1 0)
    (while (!= S 0) (<> (util 2 1 0)))))
 (define-proc 5
   (<>
    (util 2 0 0)
    (proc 16)
    (util 2 1 0)
    (while (!= S 0) (<> (util 2 1 0)))
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 1)))
 (define-proc 44
   (<>
    (animate 7)
    (color 7)
    (set-arr~ @ 6 1)
    (box 8 0 71 287)
    (set-arr~ @ 6 0)
    (set-var I 0)
    (while
     (!= I 144)
     (<>
      (blit 8 (* I 2) 71 (* I 2) 1 8 (* I 2) 0)
      (blit 8 (- 287 (* I 2)) 71 (- 287 (* I 2)) 1 8 (- 287 (* I 2)) 0)
      (set-var I (+ I 1))))
    (set-arr~ @ 31 0 0 0 0 0 0 0 4095 0 0 0 1622 2972 0 0 0)))
 (define-proc 54
   (<>
    (proc 58)
    (set-var Y 499)
    (set-arr~ @ 48 (~ X Y))
    (proc 59)
    (if (!= I (~ @ 48))
      (<>
       (proc 58)
       (set-var Y 499)
       (set-arr~ X Y I)
       (proc 59)
       (sound 1)
       (set-arr~ @ 48 (~ @ 7))
       (set-arr~ @ 7 3)
       (cond
        ((== I 0) (<> (load "KOZUE.M" (~ @ 3))))
        ((== I 1) (<> (load "_GENKI1.M" (~ @ 3))))
        ((== I 2) (<> (load "_GIBO.M" (~ @ 3))))
        ((== I 3) (<> (load "_AKOGARE.M" (~ @ 3))))
        ((== I 4) (<> (load "_SETUNAI.M" (~ @ 3))))
        ((== I 5) (<> (load "_TANOSII.M" (~ @ 3))))
        ((== I 6) (<> (load "_KANASII.M" (~ @ 3))))
        ((== I 7) (<> (load "IZUMI.M" (~ @ 3))))
        ((== I 8) (<> (load "ORG.M" (~ @ 3))))
        ((== I 9) (<> (load "AZUMI.M" (~ @ 3))))
        ((== I 10) (<> (load "_SKLAK.M" (~ @ 3))))
        ((== I 11) (<> (load "YUI.M" (~ @ 3))))
        ((== I 12) (<> (load "MISAKO.M" (~ @ 3))))
        ((== I 13) (<> (load "YOKO.M" (~ @ 3))))
        ((== I 14) (<> (load "DREAM.M" (~ @ 3))))
        ((== I 15) (<> (load "KAREN.M" (~ @ 3))))
        ((== I 16) (<> (load "SAKULAKO.M" (~ @ 3))))
        ((== I 17) (<> (load "MIREI.M" (~ @ 3))))
        ((== I 18) (<> (load "SWEET.M" (~ @ 3))))
        ((== I 19) (<> (load "KUMIKO.M" (~ @ 3))))
        ((== I 20) (<> (load "MISATO.M" (~ @ 3))))
        ((== I 21) (<> (load "_DOLAMA1.M" (~ @ 3))))
        ((== I 22) (<> (load "SACHIKO.M" (~ @ 3))))
        ((== I 23) (<> (load "IDO_1.M" (~ @ 3))))
        ((== I 24) (<> (load "_SCHIK2.M" (~ @ 3))))
        ((== I 25) (<> (load "MINOLI.M" (~ @ 3))))
        ((== I 26) (<> (load "XMAS.M" (~ @ 3))))
        ((== I 27) (<> (load "MISA.M" (~ @ 3))))
        ((== I 28) (<> (load "TOMOMI.M" (~ @ 3))))
        ((== I 29) (<> (load "DREAM_2.M" (~ @ 3))))
        ((== I 30) (<> (load "WAVE.M" (~ @ 3))))
        ((== I 31) (<> (load "XMAS_4.M" (~ @ 3))))
        ((== I 32) (<> (load "COMBINI.M" (~ @ 3))))
        ((== I 33) (<> (load "SINKAN.M" (~ @ 3))))
        ((== I 34) (<> (load "SAIONJI.M" (~ @ 3))))
        ((== I 35) (<> (load "KOTO_3.M" (~ @ 3))))
        ((== I 36) (<> (load "BUKIMI.M" (~ @ 3))))
        ((== I 37) (<> (load "TRAIN_1.M" (~ @ 3))))
        ((== I 38) (<> (load "AKILA.M" (~ @ 3))))
        ((== I 39) (<> (load "SAD.M" (~ @ 3))))
        ((== I 40) (<> (load "HAPPY3.M" (~ @ 3))))
        ((== I 41) (<> (load "SWEET_EN.M" (~ @ 3))))
        ((== I 42) (<> (load "CHIME.M" (~ @ 3))))
        ((== I 43) (<> (load "QUIZ.M" (~ @ 3))))
        ((== I 44) (<> (load "STAFF.M" (~ @ 3))))
        ((== I 45) (<> (load "URANAI.M" (~ @ 3)))))
       (if (< I 46) (<> (sound 0)))
       (set-arr~ @ 7 (~ @ 48))))))
 (define-proc 9
   (<>
    (set-arr~ @ 7 (~ @ 48))
    (proc 58)
    (set-var Y 499)
    (set-arr~ X Y 65535)
    (proc 59)
    (sound 0)))
 (define-proc 45
   (<>
    (if (< I 9)
      (<>
       (if-else (> I 4)
         (<> (set-arr~ @ 49 160) (set-var I (- I 5)))
         (<> (set-arr~ @ 49 97)))
       (set-arr~ @ 48 (+ 40 (* I 8)))
       (blit (~ @ 48) (~ @ 49) (+ (~ @ 48) 7) (+ (~ @ 49) 62) 3 3 323 0)))))
 (define-proc 8
   (<>
    (if (!= (: 2013) 15) (<> (animate 3 (: 2013))))
    (set-reg: 2013 I)
    (animate 0 I I)
    (animate 1 I)))
 (define-proc 7
   (<>
    (if (!= (: 2013) 15) (<> (animate 3 (: 2013))))
    (set-reg: 2013 I)
    (animate 0 I I)
    (animate 4 I)))
 (if (== (: 2012) 1)
   (<> (set-reg: 2012 0) (set-arr~ @ 6 0) (color 7) (box 33 292 46 312)))
 (set-arr~ @ 9 (// (~ @ 9) 128))
 (set-arr~ @ 1 0)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 53248)
 (set-arr~ @ 9 (// (~ @ 9) 128))
 (set-var W 10)
 (set-reg: 2025 0)
 (set-reg: 2022 0)
 (set-reg: 2028 0)
 (define-proc 0
   (<>
    (set-arr~ @ 9 (// (~ @ 9) 8))
    (call (+ (~ @ 0) 1100))
    (set-arr~ @ 9 (&& (~ @ 9) 65527))))
 (set-var A 10)
 (proc 13)
 (proc 11)
 (set-arr~ @ 9 (&& (~ @ 9) 65534))
 (set-arr~ @ 7 3)
 (set-arr~ @ 6 1)
 (image "04.gp4")
 (set-arr~ @ 6 0)
 (set-arr~ @ 7 1)
 (proc 15)
 (proc 22)
 (set-arr~ @ 48 (~ @ 7))
 (set-arr~ @ 7 1)
 (load "04.a6" 34816)
 (set-arr~ @ 7 (~ @ 48))
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (proc 23)
 (if (== H 1307)
   (<>
    (set-var I 7)
    (proc 45)
    (set-var I 45)
    (proc 54)
    (text "【夢仙人】こりゃあ、もう１月７日じゃぞお！！")
    (wait)
    (text "【夢仙人】最後の冬休みもこれでおしまいじゃ、あとは大人しく審判を待つがよいぞ！！")
    (wait)
    (text "【")
    (proc 0)
    (text "】どわわわわっ！？")
    (wait)
    (set-var I 0)
    (proc 45)
    (palette 3 4095)
    (palette 3)
    (palette 3 4095)
    (palette 3)
    (palette 3 4095)
    (palette 3)
    (mes-jump "ending1.mes")))
 (cond
  ((&&
    (> H 1221)
    (< H 1228)
    (> T 759)
    (< T 1501)
    (== (: 906) 1)
    (!= (: 910) 2)
    (== (: 915) 1)
    (== (: 914) 0))
   (<>
    (proc 58)
    (set-var Y 32)
    (set-arr~ X Y T)
    (proc 59)
    (mes-jump "izumi2.mes")))
  ((&&
    (> H 1221)
    (< H 1228)
    (> T 759)
    (< T 1501)
    (== (: 906) 1)
    (!= (: 910) 2)
    (== (: 915) 1)
    (== (: 914) 1))
   (<>
    (proc 58)
    (set-var Y 32)
    (set-arr~ @ 48 (~ X Y))
    (proc 59)
    (set-var Q (~ @ 48))
    (if (< (- T Q) 100) (<> (mes-jump "izumi2.mes"))))))
 (cond
  ((&&
    (> H 1225)
    (> T 759)
    (< T 1801)
    (== (: 1375) 0)
    (== (: 1400) 1)
    (== (: 1401) 0))
   (<>
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (set-arr~ @ 7 3)
    (set-arr~ @ 6 2)
    (image "pa.gp4")
    (proc 19)
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 1)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (proc 22)
    (set-arr~ @ 7 3)
    (load "pa.ani" 0)
    (util 0)
    (set-arr~ @ 7 0)
    (set-reg: 2013 15)
    (set-var I 0)
    (proc 8)
    (set-var I 13)
    (proc 54)
    (set-reg: 1908 1)
    (text "【洋子】あ……。")
    (wait)
    (text "【")
    (proc 0)
    (text "】（あれれ、弓道部の練習場に洋子がいる。）")
    (wait)
    (text "【洋子】この間は悪かったな、ちょっと気分が尖ってたからさ。")
    (wait)
    (text "【")
    (proc 0)
    (text "】謝らなくてもいいよ、気にしてないから。")
    (wait)
    (text "【洋子】考えてみたら、私だって悪いんだよな。")
    (wait)
    (text "【")
    (proc 0)
    (text "】ふーん、そうなんだ。")
    (wait)
    (text "【洋子】あのバイクの魅力に負けて、いったんは親父の話を了承しちまったんだから。")
    (wait)
    (text "【")
    (proc 0)
    (text "】ふーん、そうなんだ。")
    (wait)
    (text "【洋子】なんだよ、今日は根ほり葉ほり聞かないのか？")
    (wait)
    (text "【")
    (proc 0)
    (text "】へ？")
    (wait)
    (text "【洋子】いつもは、色々と聞きたがるじゃないかよ。")
    (wait)
    (text "【")
    (proc 0)
    (text "】（あまり俺が相談に乗ると、あきらの出番がなくなっちゃうからな。）")
    (wait)
    (set-var I 1)
    (proc 8)
    (text "【洋子】なに黙ってるんだよ。")
    (wait)
    (text "【")
    (proc 0)
    (text "】ははは、今日はいい天気だな。")
    (wait)
    (text "【洋子】ちぇっ、変な野郎だぜ。")
    (wait)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 7 3)
    (set-arr~ @ 6 1)
    (image "04.gp4")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 1)
    (proc 15)
    (proc 22)
    (text "【")
    (proc 0)
    (text "】……。")
    (wait)
    (text "【")
    (proc 0)
    (text "】悪かったな、変な野郎で。")
    (wait)
    (set-reg: 1401 1)))
  ((&&
    (> H 1226)
    (< H 1230)
    (> T 559)
    (< T 2301)
    (!= (: 429) 15)
    (== (: 433) 2)
    (== (: 434) 0)
    (== (: 430) 1))
   (<>
    (mes-call "tendo3.mes")
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 7 3)
    (set-arr~ @ 6 1)
    (image "04.gp4")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 1)
    (proc 15)
    (proc 22)
    (text "【")
    (proc 0)
    (text "】……。")
    (wait)
    (text "【")
    (proc 0)
    (text "】ところで天道のやつは、弓道部の練習場で何をしてたんだろ？")
    (wait)
    (set-reg: 430 2)))
  ((&& (> T 859) (< T 1601) (== (: 484) 0) (== (: 483) 1))
   (<>
    (mes-call "kozue.mes")
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 7 3)
    (set-arr~ @ 6 1)
    (image "04.gp4")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 1)
    (proc 15)
    (proc 22)
    (text "【")
    (proc 0)
    (text "】……。")
    (wait)
    (text "【")
    (proc 0)
    (text "】こずえちゃん、テニス部を辞めて弓道部に入るつもりなのかな？")
    (wait)
    (set-reg: 483 2)))
  ((&&
    (> H 1228)
    (> T 859)
    (< T 1801)
    (== (: 506) 1)
    (== (: 524) 0)
    (== (: 523) 1))
   (<>
    (mes-call "kozue17.mes")
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 7 3)
    (set-arr~ @ 6 1)
    (image "04.gp4")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 1)
    (proc 15)
    (proc 22)
    (text "【")
    (proc 0)
    (text "】……。")
    (wait)
    (text "【")
    (proc 0)
    (text "】こずえちゃんは、行ってしまったぞ。")
    (wait)
    (set-reg: 523 0)))
  ((&& (> H 1229) (== (: 810) 0) (> T 759) (< T 1801) (== (: 875) 0))
   (<>
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (set-arr~ @ 7 3)
    (set-arr~ @ 6 2)
    (image "h.gp4")
    (proc 19)
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 1)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (proc 22)
    (set-arr~ @ 7 3)
    (load "h.ani" 0)
    (util 0)
    (set-arr~ @ 7 0)
    (set-reg: 2013 15)
    (set-var I 0)
    (proc 8)
    (set-var I 17)
    (proc 54)
    (set-reg: 1908 1)
    (text "【片桐先生】あら、")
    (proc 0)
    (text "君。いつから弓道部に入ったのかしら？")
    (wait)
    (text "【")
    (proc 0)
    (text "】やだな、片桐先生。俺がどのクラブにも所属してない事を知ってるくせに。")
    (wait)
    (text "【片桐先生】もったいないわね、本当に。")
    (wait)
    (text "【")
    (proc 0)
    (text "】どうして？")
    (wait)
    (text "【片桐先生】だって")
    (proc 0)
    (text "君、運動神経だけは抜群じゃない。")
    (wait)
    (text "【")
    (proc 0)
    (text "】運動神経だけが抜群って言われたら、天道みたいじゃないかよぅ。")
    (wait)
    (text "【片桐先生】ふふふ、ごめんなさい。")
    (wait)
    (text "【")
    (proc 0)
    (text "】先生こそ弓道部の顧問じゃないのに、ここで何をしてるの？")
    (wait)
    (text "【片桐先生】ええ、いずみさんがいないかと思って。")
    (wait)
    (text "【")
    (proc 0)
    (text "】いずみのやつ、また何かしたんだな。")
    (wait)
    (text "【片桐先生】違いますよ、")
    (proc 0)
    (text "君じゃあるまいし。")
    (wait)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 7 3)
    (set-arr~ @ 6 1)
    (image "04.gp4")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 1)
    (proc 15)
    (proc 22)
    (text "【")
    (proc 0)
    (text "】……。")
    (wait)
    (text "【")
    (proc 0)
    (text "】き、傷つくな……ちくしょう。")
    (wait)
    (set-reg: 875 1)))
  ((&&
    (> H 1227)
    (< H 1301)
    (> T 759)
    (< T 1801)
    (== (: 973) 1)
    (== (: 906) 1)
    (== (: 910) 2)
    (== (: 982) 0))
   (<>
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (set-arr~ @ 7 3)
    (set-arr~ @ 6 2)
    (image "f.gp4")
    (proc 19)
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 1)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (proc 22)
    (set-arr~ @ 7 3)
    (load "f.ani" 0)
    (util 0)
    (set-arr~ @ 7 0)
    (set-reg: 2013 15)
    (set-var I 0)
    (proc 8)
    (set-var I 7)
    (proc 54)
    (set-reg: 1908 1)
    (text "【いずみ】あ……")
    (proc 0)
    (text "。")
    (wait)
    (text "【")
    (proc 0)
    (text "】なんだ、今日も練習か？")
    (wait)
    (text "【いずみ】今日は稽古着を来てないだろ？")
    (wait)
    (text "【")
    (proc 0)
    (text "】そう言われればそうだな。")
    (wait)
    (text "【いずみ】練習は２７日でおしまいにしたんだ。")
    (wait)
    (text "【")
    (proc 0)
    (text "】ふーん、そうなんだ。")
    (wait)
    (text "【いずみ】それより、")
    (proc 0)
    (text "。")
    (wait)
    (text "【")
    (proc 0)
    (text "】へ？")
    (wait)
    (text "【いずみ】芳樹のやつ、何か言ってなかったか？")
    (wait)
    (text "【")
    (proc 0)
    (text "】何かって何だ？")
    (wait)
    (text "【いずみ】まあ……")
    (proc 0)
    (text "に言うはずがないか。")
    (wait)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 7 3)
    (set-arr~ @ 6 1)
    (image "04.gp4")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 1)
    (proc 15)
    (proc 22)
    (text "【")
    (proc 0)
    (text "】……。")
    (wait)
    (text "【")
    (proc 0)
    (text "】いずみのやつ、芳樹が好きなのかな？")
    (wait)
    (text "【")
    (proc 0)
    (text "】……。")
    (wait)
    (text "【")
    (proc 0)
    (text "】ははは、まさかね。")
    (wait)
    (set-reg: 982 1)))
  ((&& (== H 1230) (< T 601) (== (: 1811) 1) (== (: 1838) 0))
   (<>
    (mes-call "botsu.mes")
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 7 3)
    (set-arr~ @ 6 1)
    (image "04.gp4")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 1)
    (proc 15)
    (proc 22)
    (text "【")
    (proc 0)
    (text "】……。")
    (wait)
    (text "【")
    (proc 0)
    (text "】う、後ろ姿がもの悲しすぎるぅ。")
    (wait)
    (set-reg: 1838 1)))
  ((&&
    (> H 1229)
    (> T 759)
    (< T 1801)
    (== (: 1082) 1)
    (== (: 1419) 0)
    (== (: 1424) 1)
    (== (: 1425) 0))
   (<>
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (set-arr~ @ 7 3)
    (set-arr~ @ 6 2)
    (image "w.gp4")
    (proc 19)
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 1)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (proc 22)
    (set-arr~ @ 7 3)
    (load "w.ani" 0)
    (util 0)
    (set-arr~ @ 7 0)
    (set-reg: 2013 15)
    (set-var I 0)
    (proc 8)
    (set-var I 38)
    (proc 54)
    (set-reg: 1908 1)
    (text "【あきら】……。")
    (wait)
    (text "【")
    (proc 0)
    (text "】あれれ、あきら。")
    (wait)
    (text "【あきら】……はあ。")
    (wait)
    (text "【")
    (proc 0)
    (text "】ど、どうしたんだよ。")
    (wait)
    (text "【あきら】洋子って……かわいいよな。")
    (wait)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 7 3)
    (set-arr~ @ 6 1)
    (image "04.gp4")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 1)
    (proc 15)
    (proc 22)
    (text "【")
    (proc 0)
    (text "】……。")
    (wait)
    (text "【")
    (proc 0)
    (text "】なんだあいつ、のろけてやがる。")
    (wait)
    (set-reg: 1425 1)))
  ((&&
    (> H 1224)
    (> T 759)
    (< T 1801)
    (== (: 1589) 0)
    (== (: 1598) 0)
    (== (: 1612) 1)
    (== (: 1613) 0))
   (<>
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (set-arr~ @ 7 3)
    (set-arr~ @ 6 2)
    (image "r.gp4")
    (proc 19)
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 1)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (proc 22)
    (set-arr~ @ 7 3)
    (load "r.ani" 0)
    (util 0)
    (set-arr~ @ 7 0)
    (set-reg: 2013 15)
    (set-var I 0)
    (proc 8)
    (set-var I 11)
    (proc 54)
    (set-reg: 1908 1)
    (text "【唯】あれえ、お兄ちゃんも学校に来てたんだ。")
    (wait)
    (text "【")
    (proc 0)
    (text "】唯、練習場で何をしてるんだよ。")
    (wait)
    (text "【唯】うん、西御寺君と話をしてたの。")
    (wait)
    (text "【")
    (proc 0)
    (text "】ま、また西御寺なのか！？")
    (wait)
    (text "【唯】あはは、嘘だよ。今日はいずみちゃんと話をしてたんだよ。")
    (wait)
    (text "【")
    (proc 0)
    (text "】（お、俺の事をからかってやがる。）")
    (wait)
    (text "【唯】いずみちゃんにね、色々と相談に乗ってもらってたんだ。")
    (wait)
    (text "【")
    (proc 0)
    (text "】（唯のやつ、何の相談をしてたんだろ？）")
    (wait)
    (text "【唯】お兄ちゃん。")
    (wait)
    (text "【")
    (proc 0)
    (text "】なんだよ。")
    (wait)
    (text "【唯】唯、約束があるから行くね。")
    (wait)
    (text "【")
    (proc 0)
    (text "】あ、ああ。")
    (wait)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 7 3)
    (set-arr~ @ 6 1)
    (image "04.gp4")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 1)
    (proc 15)
    (proc 22)
    (text "【")
    (proc 0)
    (text "】……。")
    (wait)
    (text "【")
    (proc 0)
    (text "】どうでもいいけど、カバンまで持って来るなよな。")
    (wait)
    (set-reg: 1613 1)))
  ((&& (== H 1224) (< T 601) (== (: 1811) 1) (== (: 1832) 1))
   (<>
    (mes-call "botsu.mes")
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 7 3)
    (set-arr~ @ 6 1)
    (image "04.gp4")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 1)
    (proc 15)
    (proc 22)
    (text "【")
    (proc 0)
    (text "】……。")
    (wait)
    (text "【")
    (proc 0)
    (text "】クリスマスイブだというのに、かわいそうな女だ。")
    (wait)
    (set-reg: 1832 2)))
  ((&& (== H 1305) (< T 601) (== (: 1811) 1) (== (: 1844) 1))
   (<>
    (mes-call "botsu.mes")
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 7 3)
    (set-arr~ @ 6 1)
    (image "04.gp4")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 1)
    (proc 15)
    (proc 22)
    (text "【")
    (proc 0)
    (text "】……。")
    (wait)
    (text "【")
    (proc 0)
    (text "】ロープが、股間に食い込んでたぞ。")
    (wait)
    (set-reg: 1844 2)))
  ((&&
    (> H 1230)
    (> T 659)
    (< T 931)
    (== (: 686) 1)
    (== (: 724) 0)
    (== (: 736) 0))
   (<>
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (set-arr~ @ 7 3)
    (set-arr~ @ 6 2)
    (image "kb.gp4")
    (proc 19)
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 1)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (proc 22)
    (set-arr~ @ 7 3)
    (load "kb.ani" 0)
    (util 0)
    (set-arr~ @ 7 0)
    (set-reg: 2013 15)
    (set-var I 0)
    (proc 8)
    (set-var I 25)
    (proc 54)
    (set-reg: 1908 1)
    (text "【みのり】あ……。")
    (wait)
    (text "【")
    (proc 0)
    (text "】あれれ、みのりちゃんって弓道部だっけ？")
    (wait)
    (text "【みのり】ち、違います。")
    (wait)
    (text "【")
    (proc 0)
    (text "】そうだよね、いずみからそんな話を聞いた事はないから。")
    (wait)
    (text "【みのり】いずみさんと、仲がいいですよね。")
    (wait)
    (text "【")
    (proc 0)
    (text "】え？")
    (wait)
    (text "【みのり】")
    (proc 0)
    (text "さんって、いずみさんと仲がいいですよね。")
    (wait)
    (text "【")
    (proc 0)
    (text "】仲がいいように見える？")
    (wait)
    (text "【みのり】私より、仲がいいと思います。")
    (wait)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 7 3)
    (set-arr~ @ 6 1)
    (image "04.gp4")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 1)
    (proc 15)
    (proc 22)
    (text "【")
    (proc 0)
    (text "】……。")
    (wait)
    (text "【")
    (proc 0)
    (text "】みのりちゃんは、いずみの事をよく知らないんだよな。")
    (wait)
    (text "【")
    (proc 0)
    (text "】そう、あいつはただ馴れ馴れしいだけなんだ。")
    (wait)
    (set-reg: 736 1)))
  ((&&
    (> H 1301)
    (> T 759)
    (< T 2001)
    (== (: 983) 1)
    (== (: 1132) 0)
    (== (: 1116) 1))
   (<>
    (text "【女の声】なんか……落ち着かないな。")
    (wait)
    (text "【")
    (proc 0)
    (text "】（あれれ、この声は？）")
    (wait)
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (set-arr~ @ 7 3)
    (set-arr~ @ 6 2)
    (image "fa.gp4")
    (proc 19)
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 1)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (proc 22)
    (set-arr~ @ 7 3)
    (load "fa.ani" 0)
    (util 0)
    (set-arr~ @ 7 0)
    (set-reg: 2013 15)
    (set-var I 0)
    (proc 8)
    (set-var I 7)
    (proc 54)
    (set-reg: 1908 1)
    (text "【いずみ】きゃっ！！")
    (wait)
    (text "【")
    (proc 0)
    (text "】なんだよ、驚く事はないじゃないか。")
    (wait)
    (text "【いずみ】だ、だって、いきなり現れるからさ。")
    (wait)
    (text "【")
    (proc 0)
    (text "】それは俺のセリフだ。")
    (wait)
    (text "【いずみ】……。")
    (wait)
    (text "【")
    (proc 0)
    (text "】元気がないな、いずみ。")
    (wait)
    (text "【いずみ】こんな気持ち、初めてなんだよ。")
    (wait)
    (text "【")
    (proc 0)
    (text "】はあ？")
    (wait)
    (text "【いずみ】起きている時、ずっと一つの事しか考えられないんだぜ。")
    (wait)
    (text "【")
    (proc 0)
    (text "】セックスの事か？")
    (wait)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 7 3)
    (set-arr~ @ 6 1)
    (image "04.gp4")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 1)
    (proc 15)
    (proc 22)
    (text "【")
    (proc 0)
    (text "】……。")
    (wait)
    (text "【")
    (proc 0)
    (text "】おーい、いずみっ！！")
    (wait)
    (set-reg: 1132 1)))
  ((&&
    (== H 1304)
    (> T 759)
    (< T 1801)
    (== (: 1589) 0)
    (== (: 1598) 0)
    (== (: 1702) 0))
   (<>
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (set-arr~ @ 7 3)
    (set-arr~ @ 6 2)
    (image "r.gp4")
    (proc 19)
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 1)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (proc 22)
    (set-arr~ @ 7 3)
    (load "r.ani" 0)
    (util 0)
    (set-arr~ @ 7 0)
    (set-reg: 2013 15)
    (set-var I 0)
    (proc 8)
    (set-var I 11)
    (proc 54)
    (set-reg: 1908 1)
    (text "【唯】あれえ、お兄ちゃんだ。")
    (wait)
    (text "【")
    (proc 0)
    (text "】唯、弓道部にでも入ったのか？")
    (wait)
    (text "【唯】違うよ、いずみちゃんと話をしてたんだよ。")
    (wait)
    (text "【")
    (proc 0)
    (text "】そのいずみは、どこにいるんだよ。")
    (wait)
    (text "【唯】如月町に買い物があるって行っちゃった。")
    (wait)
    (text "【")
    (proc 0)
    (text "】なんだ、ようするに取り残されたわけだ。")
    (wait)
    (set-var I 1)
    (proc 8)
    (text "【唯】お兄ちゃんって、唯をいじめるのが好きだよね。")
    (wait)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 7 3)
    (set-arr~ @ 6 1)
    (image "04.gp4")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 1)
    (proc 15)
    (proc 22)
    (text "【")
    (proc 0)
    (text "】……。")
    (wait)
    (text "【")
    (proc 0)
    (text "】好きな女の子ほど、いじめたくなるって？")
    (wait)
    (text "【")
    (proc 0)
    (text "】ふん、そんなのは小学生までだぞ。")
    (wait)
    (set-reg: 1702 1)))
  ((&&
    (> H 1303)
    (> T 759)
    (< T 1801)
    (== (: 1724) 1)
    (== (: 1750) 1)
    (== (: 1751) 0))
   (<>
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (set-arr~ @ 7 3)
    (set-arr~ @ 6 2)
    (image "r.gp4")
    (proc 19)
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 1)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (proc 22)
    (set-arr~ @ 7 3)
    (load "r.ani" 0)
    (util 0)
    (set-arr~ @ 7 0)
    (set-reg: 2013 15)
    (set-var I 0)
    (proc 8)
    (set-var I 11)
    (proc 54)
    (set-reg: 1908 1)
    (text "【唯】あ……お兄ちゃん。")
    (wait)
    (text "【")
    (proc 0)
    (text "】あれれ、いずみにでも会いに来たのか？")
    (wait)
    (text "【唯】うん、いずみちゃんと話がしたくて。")
    (wait)
    (text "【")
    (proc 0)
    (text "】何の話をするんだよ。")
    (wait)
    (text "【唯】あはは、内緒だよ。")
    (wait)
    (text "【")
    (proc 0)
    (text "】（こいつ、変な事を言うわけじゃないだろうな。）")
    (wait)
    (text "【唯】唯ね、最近眠れないんだ。")
    (wait)
    (text "【")
    (proc 0)
    (text "】はあ？")
    (wait)
    (text "【唯】目をつぶると、心臓がどきどきしてきちゃうから。")
    (wait)
    (text "【")
    (proc 0)
    (text "】ど、どうして？")
    (wait)
    (set-var I 2)
    (proc 8)
    (text "【唯】……。")
    (wait)
    (text "【唯】そういう時にね、お兄ちゃんとすごく話がしたくなるんだよ。")
    (wait)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 7 3)
    (set-arr~ @ 6 1)
    (image "04.gp4")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 1)
    (proc 15)
    (proc 22)
    (text "【")
    (proc 0)
    (text "】……。")
    (wait)
    (text "【")
    (proc 0)
    (text "】なんだよ、胸でもマッサージすればいいのか？")
    (wait)
    (set-reg: 1751 1)))
  ((&&
    (> H 1303)
    (> T 759)
    (< T 1801)
    (== (: 1082) 1)
    (== (: 1419) 0)
    (== (: 1436) 1)
    (== (: 1437) 0))
   (<>
    (text "【女の声】いずみか？")
    (wait)
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (set-arr~ @ 7 3)
    (set-arr~ @ 6 2)
    (image "pa.gp4")
    (proc 19)
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 1)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (proc 22)
    (set-arr~ @ 7 3)
    (load "pa.ani" 0)
    (util 0)
    (set-arr~ @ 7 0)
    (set-reg: 2013 15)
    (set-var I 0)
    (proc 8)
    (set-var I 13)
    (proc 54)
    (set-reg: 1908 1)
    (text "【洋子】あれれ、")
    (proc 0)
    (text "かよ。")
    (wait)
    (text "【")
    (proc 0)
    (text "】悪かったな、")
    (proc 0)
    (text "で。")
    (wait)
    (text "【洋子】そうだ、たぶんあきらから聞いてると思うけど。")
    (wait)
    (text "【")
    (proc 0)
    (text "】専門学校の話か？")
    (wait)
    (text "【洋子】ああ、あきらと一緒に専門学校へ行く事にしたんだ。")
    (wait)
    (text "【")
    (proc 0)
    (text "】二人でバイク屋でバイトして、あのバイクを買い戻すつもりかよ。")
    (wait)
    (text "【洋子】違うんだよ、そんな単純な理由じゃないんだ。")
    (wait)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 7 3)
    (set-arr~ @ 6 1)
    (image "04.gp4")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 1)
    (proc 15)
    (proc 22)
    (text "【")
    (proc 0)
    (text "】……。")
    (wait)
    (text "【")
    (proc 0)
    (text "】単純じゃないって事は、複雑な理由があるって事だよな。")
    (wait)
    (text "【")
    (proc 0)
    (text "】ちぇっ、複雑な理由なんて当事者にしかわかるはずがないよ。")
    (wait)
    (set-reg: 1437 1)))
  ((&&
    (> H 1303)
    (> T 759)
    (< T 1901)
    (== (: 906) 1)
    (== (: 910) 2)
    (== (: 1059) 0))
   (<>
    (set-arr~ @ 9 (// (~ @ 9) 1))
    (set-arr~ @ 7 3)
    (set-arr~ @ 6 2)
    (image "f.gp4")
    (proc 19)
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 1)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (proc 22)
    (set-arr~ @ 7 3)
    (load "f.ani" 0)
    (util 0)
    (set-arr~ @ 7 0)
    (set-reg: 2013 15)
    (set-var I 0)
    (proc 8)
    (set-var I 7)
    (proc 54)
    (set-reg: 1908 1)
    (text "【いずみ】よう、")
    (proc 0)
    (text "。")
    (wait)
    (text "【")
    (proc 0)
    (text "】なんだいずみ、また練習でも開始したのか？")
    (wait)
    (text "【いずみ】私は後輩が来てないかと思って、学校へ来たついでに寄ってみたんだ。")
    (wait)
    (text "【")
    (proc 0)
    (text "】そうだよな、いずみは弓道部の部長だもんな。")
    (wait)
    (text "【いずみ】そういえば次の部長を、３学期になったら決めないといけないんだ。")
    (wait)
    (text "【")
    (proc 0)
    (text "】くじ引きかなんかで決めるのか？")
    (wait)
    (text "【いずみ】弓道部は部員の投票で決めるのが恒例なんだ。")
    (wait)
    (text "【")
    (proc 0)
    (text "】ふーん、そうだったんだ。")
    (wait)
    (text "【いずみ】さてと、私はもう行くぜ。")
    (wait)
    (set-arr~ @ 9 (&& (~ @ 9) 65534))
    (set-arr~ @ 7 3)
    (set-arr~ @ 6 1)
    (image "04.gp4")
    (set-arr~ @ 6 0)
    (set-arr~ @ 7 1)
    (proc 15)
    (proc 22)
    (text "【")
    (proc 0)
    (text "】……。")
    (wait)
    (text "【")
    (proc 0)
    (text "】って事は、いずみもみんなから推されて部長になったんだ。")
    (wait)
    (text "【")
    (proc 0)
    (text "】ふーん、いずみってけっこう人望があるやつなんだな。")
    (wait)
    (set-reg: 1059 1)))
  (else (<> (set-reg: 2028 1))))
 (cond
  ((&& (== H 1224) (== (: 1908) 1))
   (<> (set-var I 26) (proc 54) (set-reg: 1908 0)))
  ((&& (== H 1301) (== (: 1908) 1))
   (<> (set-var I 35) (proc 54) (set-reg: 1908 0)))
  ((&& (!= H 1224) (!= H 1301) (== (: 1908) 1))
   (<> (set-var I 32) (proc 54) (set-reg: 1908 0))))
 (if (== (: 2028) 1)
   (<>
    (cond
     ((== (: 121) 0)
      (<>
       (text "【")
       (proc 0)
       (text "】ここは八十八学園、弓道部の練習場だぞ。")
       (wait)
       (set-reg: 121 1)))
     ((== (: 121) 1)
      (<>
       (cond
        ((&& (> T 759) (< T 900))
         (<> (text "【") (proc 0) (text "】弓道部の練習場だぞ。") (wait)))
        ((&& (> T 859) (< T 1700))
         (<>
          (text "【")
          (proc 0)
          (text "】ここは弓道部の練習場だ。うちの学校って、設備だけは整っているよなぁ。")
          (wait)))
        ((&& (> T 1659) (< T 1900))
         (<>
          (text "【")
          (proc 0)
          (text "】おーい、誰かいないのかっ！？")
          (wait)
          (text "【")
          (proc 0)
          (text "】……。")
          (wait)
          (text "【")
          (proc 0)
          (text "】ふん、誰もいないようだぞ。")
          (wait)))
        ((> T 1859)
         (<> (text "【") (proc 0) (text "】な、なんか……まわりが暗いと恐い雰囲気だぞ。") (wait)))
        ((&& (> T 0) (< T 300))
         (<>
          (text "【")
          (proc 0)
          (text "】……。")
          (wait)
          (text "【")
          (proc 0)
          (text "】こんな時間に、ここへ来るんじゃなかった。")
          (wait)))
        ((&& (> T 259) (< T 600))
         (<> (text "【") (proc 0) (text "】誰もいない……当たり前か。") (wait)))
        ((&& (> T 559) (< T 800))
         (<>
          (text "【")
          (proc 0)
          (text "】こんな朝早くから練習してるとしたら、たぶんいずみぐらいだろう。")
          (wait)
          (text "【")
          (proc 0)
          (text "】……。")
          (wait)
          (text "【")
          (proc 0)
          (text "】と言いつつ、誰もいないじゃないか……ははは。")
          (wait)))
        (else
         (<> (text "【") (proc 0) (text "】ここは八十八学園、弓道部の練習場だ。") (wait)))))))))
 (set-reg: 10 0)
 (set-reg: 11 0)
 (set-reg: 12 0)
 (set-reg: 13 0)
 (set-reg: 14 0)
 (set-reg: 15 0)
 (set-reg: 16 0)
 (set-reg: 17 0)
 (set-reg: 18 0)
 (set-reg: 19 0)
 (set-reg: 20 0)
 (set-reg: 21 0)
 (set-reg: 22 0)
 (set-reg: 23 0)
 (set-reg: 24 0)
 (set-reg: 25 0)
 (set-reg: 26 0)
 (set-reg: 27 0)
 (set-reg: 28 0)
 (set-reg: 29 0)
 (set-reg: 30 0)
 (set-reg: 31 0)
 (set-reg: 32 0)
 (set-reg: 33 0)
 (set-reg: 34 0)
 (set-reg: 35 0)
 (set-reg: 36 0)
 (set-reg: 37 0)
 (set-reg: 38 0)
 (set-reg: 39 0)
 (set-reg: 40 0)
 (set-reg: 41 0)
 (set-reg: 42 0)
 (set-reg: 43 0)
 (set-reg: 44 0)
 (set-reg: 45 0)
 (set-reg: 46 0)
 (set-reg: 47 0)
 (set-reg: 48 0)
 (set-reg: 49 0)
 (set-reg: 50 0)
 (while
  (== 1 1)
  (<>
   (proc 21)
   (menu-show (<>))
   (proc 23)
   (cond
    ((== V 0)
     (<>
      (clear)
      (proc 20)
      (set-reg: 1001 0)
      (menu-show
       (<.>
        (text "校庭へ戻る")
        (text "体育館へ行く")
        (text "体育館裏へ行く")
        (text "まだここにいる")
        (if (&&
             (== H 1229)
             (> T 1030)
             (< T 1131)
             (== (: 658) 1)
             (== (: 681) 0))
          (text "ネット裏に行ってみる"))))
      (cond
       ((== N 1)
        (<>
         (text "【")
         (proc 0)
         (text "】そうだな、校庭に戻るか……。")
         (wait)
         (mes-jump "05.mes")))
       ((== N 2)
        (<>
         (text "【")
         (proc 0)
         (text "】よーし、体育館へ行こう。")
         (wait)
         (mes-jump "06.mes")))
       ((== N 3)
        (<>
         (text "【")
         (proc 0)
         (text "】よーし、体育館裏へ行こう。")
         (wait)
         (mes-jump "07.mes")))
       ((== N 4) (<> (text "【") (proc 0) (text "】え……まだここにいるの？") (wait)))
       ((== N 5)
        (<>
         (text "【")
         (proc 0)
         (text "】どうせ西御寺が、誰かにからかわれてると思うが。")
         (wait)
         (text "【")
         (proc 0)
         (text "】……。")
         (wait)
         (text "【")
         (proc 0)
         (text "】一応確認の為に、ネット裏へ行ってみるか。")
         (wait)
         (proc 44)
         (text "【")
         (proc 0)
         (text "】（……。）")
         (wait)
         (text "【")
         (proc 0)
         (text "】（ははは、西御寺のやつが一人で立ち尽くしてたりして。）")
         (wait)
         (text "【")
         (proc 0)
         (text "】（……。）")
         (wait)
         (text "【")
         (proc 0)
         (text "】（話し声が……聞こえてくる。）")
         (wait)
         (text "【")
         (proc 0)
         (text "】（……。）")
         (wait)
         (text "【")
         (proc 0)
         (text "】（えーっ！？）")
         (wait)
         (set-reg: 681 1)
         (mes-jump "minori2.mes")))
       (else (<>)))))
    ((&& (== V 1) (== N 1) (== (: 10) 0))
     (<>
      (text "【")
      (proc 0)
      (text "】ぶっとい柱だな……練習する時、邪魔じゃないのか？")
      (wait)
      (text "【")
      (proc 0)
      (text "】……。")
      (wait)
      (text "【")
      (proc 0)
      (text "】ははは、この柱の間に一人ずつ立って、弓を引くようになってるようだ……ちっとも邪魔じゃない。")
      (wait)
      (set-reg: 10 1)))
    ((&& (== V 1) (== N 1) (== (: 10) 1))
     (<>
      (text "【")
      (proc 0)
      (text "】等間隔で、柱が屋根を支えている。")
      (wait)
      (text "【")
      (proc 0)
      (text "】この柱に切り込みを入れておけば、ちょっとした衝撃でメリメリと……。")
      (wait)
      (text "【")
      (proc 0)
      (text "】……。")
      (wait)
      (text "【")
      (proc 0)
      (text "】いずみを殺してどうするんだよ、まったく。")
      (wait)
      (set-reg: 10 2)))
    ((&& (== V 1) (== N 1) (== (: 10) 2))
     (<>
      (text "【")
      (proc 0)
      (text "】背中がかゆい時に、ちょうどいい柱だ。もっともそんな事に使用してるのをいずみに見られたら、弓の切っ先を俺様に向けるだろう。")
      (wait)
      (set-reg: 10 3)))
    ((&& (== V 1) (== N 1) (== (: 10) 3))
     (<> (text "【") (proc 0) (text "】この柱、桧じゃないか……金かけてるなぁ。") (wait)))
    ((&& (== V 1) (== N 2) (== (: 11) 0))
     (<>
      (text "【")
      (proc 0)
      (text "】雨天でも練習できるように、ちゃんと屋根がついている。それとも日焼け防止の為に屋根がつけられているのか？")
      (wait)
      (set-reg: 11 1)))
    ((&& (== V 1) (== N 2) (== (: 11) 1))
     (<>
      (text "【")
      (proc 0)
      (text "】雨が降っても、雪が降っても、象が降っても練習できる。オールウェザー対応の屋根だ。")
      (wait)
      (set-reg: 11 2)))
    ((&& (== V 1) (== N 2) (== (: 11) 2))
     (<>
      (text "【")
      (proc 0)
      (text "】確かに雨が降っても練習できるけど、雨の音がバタバタとうるさそうだぞ。")
      (wait)
      (set-reg: 11 3)))
    ((&& (== V 1) (== N 2) (== (: 11) 3))
     (<>
      (text "【")
      (proc 0)
      (text "】あれれ……屋根の隅に、ツバメの巣があるよ。")
      (wait)
      (set-reg: 11 4)))
    ((&& (== V 1) (== N 2) (== (: 11) 4))
     (<>
      (text "【")
      (proc 0)
      (text "】ここからでは見えないが、たぶん瓦敷きの屋根だろう。プレハプ住宅のような屋根だったら、情緒も何もあったもんじゃない。")
      (wait)))
    ((&& (== V 1) (== N 3) (== (: 12) 0))
     (<>
      (text "【")
      (proc 0)
      (text "】校庭につけられた照明が顔を覗かせている。あの照明が点灯すると、それこそグランドが昼間のように明るくなるんだ。")
      (wait)
      (text "【")
      (proc 0)
      (text "】ちなみにグラインドは、腰をうねうねと回す事だぞ。")
      (wait)
      (set-reg: 12 1)))
    ((&& (== V 1) (== N 3) (== (: 12) 1))
     (<>
      (text "【")
      (proc 0)
      (text "】校庭を照らす為の照明だ……もちろん今は使われてない。")
      (wait)
      (set-reg: 12 2)))
    ((&& (== V 1) (== N 3) (== (: 12) 2))
     (<>
      (text "【")
      (proc 0)
      (text "】スタジアムにあるような照明だぞ。野球部ばかり、どうして待遇がいいんだろ？")
      (wait)
      (text "【")
      (proc 0)
      (text "】弱いくせに、ちっ。")
      (wait)
      (set-reg: 12 3)))
    ((&& (== V 1) (== N 3) (== (: 12) 3))
     (<>
      (text "【")
      (proc 0)
      (text "】だいたいうちの学校に野球部がある事自体、不思議なんだ。")
      (wait)
      (text "【")
      (proc 0)
      (text "】髪を染めたやつはいるわ、モヒカン刈りはいるわ、眉毛ハゲまでいるわ……高野連がそんな連中を認めるわけがないじゃないか。")
      (wait)
      (set-reg: 12 4)))
    ((&& (== V 1) (== N 3) (== (: 12) 4))
     (<>
      (text "【")
      (proc 0)
      (text "】どうせ金をかけるんだったら、ドーム球場にすればいいんだ。やるんだったら、徹底的にやったほうが面白いもんな。")
      (wait)))
    ((&& (== V 1) (== N 4) (== (: 13) 0))
     (<>
      (text "【")
      (proc 0)
      (text "】的が５つ並んでいる。微妙に形が違うように見えるのは、俺の目の錯覚だろうか？")
      (wait)
      (set-reg: 13 1)))
    ((&& (== V 1) (== N 4) (== (: 13) 1))
     (<>
      (text "【")
      (proc 0)
      (text "】いずみはここに立って、あの的めがけてきりきりと弓を引き……。")
      (wait)
      (text "【")
      (proc 0)
      (text "】……。")
      (wait)
      (text "【")
      (proc 0)
      (text "】なんか……色っぽいよな。")
      (wait)
      (set-reg: 13 2)))
    ((&& (== V 1) (== N 4) (== (: 13) 2))
     (<>
      (text "【")
      (proc 0)
      (text "】弓道部で使っている的だ。ここからではわからないが、そばで見たら穴だらけのはずだぞ。")
      (wait)))
    ((&& (== V 1) (== N 5) (== (: 122) 0))
     (<>
      (text "【")
      (proc 0)
      (text "】なんか文字が書いてあるぞ……なになに、真美？")
      (wait)
      (text "【")
      (proc 0)
      (text "】……。")
      (wait)
      (text "【")
      (proc 0)
      (text "】そうか、真美っていう女の子の名前だな。")
      (wait)
      (set-reg: 122 1)))
    ((&& (== V 1) (== N 5) (== (: 14) 0))
     (<> (text "【") (proc 0) (text "】的の上には幕が張られている。") (wait) (set-reg: 14 1)))
    ((&& (== V 1) (== N 5) (== (: 14) 1))
     (<>
      (text "【")
      (proc 0)
      (text "】学園の雰囲気からすると、この場所だけトリップしてる感じがする。")
      (wait)
      (set-reg: 14 2)))
    ((&& (== V 1) (== N 5) (== (: 14) 2))
     (<>
      (text "【")
      (proc 0)
      (text "】真美ちゃんを応援する為の幕だ……もっとも、俺は真美ちゃんなんて知らないが。")
      (wait)))
    ((&& (== V 1) (== N 6) (== (: 15) 0))
     (<>
      (text "【")
      (proc 0)
      (text "】はずれた矢は、ここにぐさぐさと刺さるんだ。")
      (wait)
      (text "【")
      (proc 0)
      (text "】ああ、俺も股間の矢を女の子に刺した〜いっ。")
      (wait)
      (text "【")
      (proc 0)
      (text "】蝶のように舞い、蜂のように刺し、そして蝿のように逃げるんだ。")
      (wait)
      (set-reg: 15 1)))
    ((&& (== V 1) (== N 6) (== (: 15) 1))
     (<>
      (text "【")
      (proc 0)
      (text "】的の間に、弓道部の１年生を立たせるってのはどうだ？")
      (wait)
      (text "【")
      (proc 0)
      (text "】……。")
      (wait)
      (text "【")
      (proc 0)
      (text "】うーん、いぢめで訴えられるな。")
      (wait)
      (set-reg: 15 2)))
    ((&& (== V 1) (== N 6) (== (: 15) 2))
     (<>
      (text "【")
      (proc 0)
      (text "】この的に、いずみの似顔絵を描いておいたら……怒るだろうな、やっぱり。")
      (wait)
      (text "【")
      (proc 0)
      (text "】でも下級生の腕前が、急に上がったりして……ひっひっひっ。")
      (wait)))
    ((&& (== V 1) (== N 7) (== (: 16) 0))
     (<>
      (text "【")
      (proc 0)
      (text "】グランドにあるネットだ……偉そうにそびえ立っている。")
      (wait)
      (set-reg: 16 1)))
    ((&& (== V 1) (== N 7) (== (: 16) 1))
     (<>
      (text "【")
      (proc 0)
      (text "】これがないと、ボールがグランドの外に飛び出してしまう。")
      (wait)
      (set-reg: 16 2)))
    ((&& (== V 1) (== N 7) (== (: 16) 2))
     (<>
      (text "【")
      (proc 0)
      (text "】あそこに的をつけたら、弓道部の連中は狙ってくれるかな？")
      (wait)
      (text "【")
      (proc 0)
      (text "】それより野球部の帽子に的を書くほうが面白いな……ほとんどサバイバルゲームだよ、こりゃ。")
      (wait)))
    ((&& (== V 1) (== N 8) (== (: 17) 0))
     (<>
      (text "【")
      (proc 0)
      (text "】練習場の両側には、なぜか植え込みがある。")
      (wait)
      (set-reg: 17 1)))
    ((&& (== V 1) (== N 8) (== (: 17) 1))
     (<>
      (text "【")
      (proc 0)
      (text "】わざわざ植えたのか、あるいは雑草が大きくなっただけなのか……うーん、謎だな。")
      (wait)
      (set-reg: 17 2)))
    ((&& (== V 1) (== N 8) (== (: 17) 2))
     (<>
      (text "【")
      (proc 0)
      (text "】さすがの俺様も、弓道部の練習中に、この植え込みの中にいる勇気はない。")
      (wait)
      (text "【")
      (proc 0)
      (text "】もっともそれは勇気とは言わず、ただ単に無茶な事をしてるだけか。")
      (wait)
      (set-reg: 17 3)))
    ((&& (== V 1) (== N 8) (== (: 17) 3))
     (<> (text "【") (proc 0) (text "】植え込みか雑草か、どちらかだ。") (wait)))
    ((&& (== V 1) (== N 9) (== (: 18) 0))
     (<>
      (text "【")
      (proc 0)
      (text "】この練習場自体、樹木に囲まれている。矢が外に飛び出さないように植えてあるのか？")
      (wait)
      (set-reg: 18 1)))
    ((&& (== V 1) (== N 9) (== (: 18) 1))
     (<>
      (text "【")
      (proc 0)
      (text "】緑が生い茂っている。ちなみに俺様が生えてきたのは、中学の２年の頃だ。")
      (wait)
      (set-reg: 18 2)))
    ((&& (== V 1) (== N 9) (== (: 18) 2))
     (<>
      (text "【")
      (proc 0)
      (text "】夏になるとセミがうるさいって、いずみが言ってたっけ。たしかにこう樹木が生い茂ってたら、セミも寄ってくるだろう。")
      (wait)))
    ((&& (== V 1) (== N 10) (> T 759) (< T 900) (== (: 19) 0))
     (<>
      (text "【")
      (proc 0)
      (text "】なんていい天気なんだ……全て俺様のおかげだな。")
      (wait)
      (set-reg: 19 1)))
    ((&& (== V 1) (== N 10) (> T 759) (< T 900) (== (: 19) 1))
     (<>
      (text "【")
      (proc 0)
      (text "】空は抜けるように青く、雲は俺の頭の中のように白い……って、自分で自分を落としてどうするんだよっ。")
      (wait)))
    ((&& (== V 1) (== N 10) (> T 1700) (< T 1800) (== (: 19) 0))
     (<>
      (text "【")
      (proc 0)
      (text "】もう夕方か……最近、時間が経つのが早いな。")
      (wait)
      (set-reg: 19 1)))
    ((&& (== V 1) (== N 10) (> T 1700) (< T 1800) (== (: 19) 1))
     (<> (text "【") (proc 0) (text "】だんだん青い空が、濃紺になっていく……。") (wait)))
    ((&& (== V 1) (== N 10) (> T 1800) (< T 2359) (== (: 19) 0))
     (<> (text "【") (proc 0) (text "】星がきれいだな……うんうん。") (wait) (set-reg: 19 1)))
    ((&& (== V 1) (== N 10) (> T 1800) (< T 2359) (== (: 19) 1))
     (<> (text "【") (proc 0) (text "】きれいな夜空だ……あしたもいい天気になるだろう。") (wait)))
    ((&& (== V 1) (== N 10) (== (: 19) 0))
     (<>
      (text "【")
      (proc 0)
      (text "】弓道部の練習場から見上げる空……か。")
      (wait)
      (set-reg: 19 1)))
    ((&& (== V 1) (== N 10) (== (: 19) 1))
     (<> (text "【") (proc 0) (text "】空を見るより、もっと他にする事があるだろ？") (wait)))
    ((&& (== V 1) (== N 11) (== (: 20) 0))
     (<>
      (text "【")
      (proc 0)
      (text "】ここは八十八学園の、弓道部練習場だ。そして同級生のいずみは、弓道部の部長をやってるんだよな。")
      (wait)
      (set-reg: 20 1)))
    ((&& (== V 1) (== N 11) (== (: 20) 1))
     (<>
      (text "【")
      (proc 0)
      (text "】だからあ、ここは弓道部の練習場だってば。あきらが言ってたが、いずみにあこがれて弓道部に入るやつも多いそうだ。")
      (wait)
      (set-reg: 20 2)))
    ((&& (== V 1) (== N 11) (== (: 20) 2))
     (<>
      (text "【")
      (proc 0)
      (text "】弓道部の練習場には俺しかいない……いずみは、どこで何をしてるんだ？")
      (wait)
      (text "【")
      (proc 0)
      (text "】……。")
      (wait)
      (text "【")
      (proc 0)
      (text "】お風呂にでも入ってるのかな？")
      (wait)
      (set-reg: 20 3)))
    ((&& (== V 1) (== N 11) (== (: 20) 3))
     (<>
      (text "【")
      (proc 0)
      (text "】いずみは弓道部の練習場にいない。だいたい俺はここへ何をしに来たんだろう。")
      (wait)))
    ((&& (== V 1) (== N 12) (== (: 21) 0))
     (<> (text "【") (proc 0) (text "】あの建物は、弓道部の部室かな？") (wait) (set-reg: 21 1)))
    ((&& (== V 1) (== N 12) (== (: 21) 1))
     (<>
      (text "【")
      (proc 0)
      (text "】なんか、普通の一軒家のように見えるぞ。")
      (wait)
      (set-reg: 21 2)))
    ((&& (== V 1) (== N 12) (== (: 21) 2))
     (<> (text "【") (proc 0) (text "】考えるのが面倒だ、あの建物は弓道部の部室にしてしまおう。") (wait)))
    (else (<>))))))