(mes
 (meta (engine 'AI1) (charset "pc98"))
 (define-proc 10
   (<>
    (if (== (: 1) 0)
      (<>
       (text-color 5)
       (if-else (== (? 10) 9)
         (<>
          (screen 20 (<> (clear 6) (wait 1) (clear 0) (wait 1)))
          (text "かいしんの一撃！！")
          (wait 50)
          (set-var J (* (- (~ M 1) (~ E 2)) 2)))
         (<>
          (screen 5 (<> (clear 6) (wait 1) (clear 0) (wait 1)))
		  (text "I attack!\n")
          (wait 50)
          (if-else (&&
                    (> (~ E 3) (~ M 3))
                    (> (- (~ E 3) (~ M 3)) (/ (~ M 3) (+ (? 3) 2))))
            (<> (text "I was annihilated.") (set-var J 0))
            (<>
             (if-else (> (~ E 2) (~ M 1))
               (<>
                (call G)
                (text " began to smile.\n")
                (text "It seems they have no teeth! Yuck!")
                (set-var J 0))
               (<>
				(text "I ")
                (set-var J (? 3))
                (if (== J 0) (<> (text "rubbed ") (call G) (text " tits!")))
                (if (== J 1) (<> (text "muttered risque innuendos!")))
                (if (== J 2) (<> (text "kissed ") (call G) (text "!")))
                (set-var J (+ (- (~ M 1) (~ E 2)) (? 10) 1))))))))
       (wait 50)
       (if (!= J 0)
         (<>
          (text "\n")
          (call G)
          (text " took ")
          (set-arr~ @ 7 31)
          (text (number J) "damage!")
          (if-else (> J (~ E 0))
            (<>
             (set-arr~ E 0 0)
             (wait 150)
             (recover)
             (image B)
             (clear)
             (call G)
             (text " was defeated!")
             (wait)
             (set-reg: 2 1)
             (break))
            (<> (set-arr~ E 0 (- (~ E 0) J))))
          (wait 150)))))))
 (define-proc 11
   (<>
    (if (== (: 2) 0)
      (<>
       (text-color 6)
       (if-else (== (? 10) 9)
         (<>
          (screen 20 (<> (clear 2) (wait 1) (clear 0) (wait 1)))
          (text "Oh no! Someone snuck up on me! ")
          (call G)
          (text "'s attack!")
          (wait 50)
          (set-var J (* (- (~ E 1) (~ M 2)) 2)))
         (<>
          (screen 5 (<> (clear 2) (wait 1) (clear 0) (wait 1)))
          (call G)
          (text "'s attack!\n")
          (wait 50)
          (if-else (&&
                    (> (~ M 3) (~ E 3))
                    (> (- (~ M 3) (~ E 3)) (/ (~ E 3) (+ (? 3) 2))))
            (<> (call F) (text "は、素早く身をかわした。") (set-var J 0))
            (<>
             (if-else (> (~ M 2) (~ E 1))
               (<>
                (call F)
                (text "は")
                (call G)
                (text "の攻撃にたえた！")
                (set-var J 0))
               (<>
                (set-var J (+ (- (~ E 1) (~ M 2)) (? 10) 1))
                (call G)
                (text "は、")
                (if (== T 1)
                  (<>
                   (set-var I (? 3))
                   (if (== I 0) (<> (call F) (text "にウインクした！")))
                   (if (== I 1) (<> (text "美しいうたをうたった！")))
                   (if (== I 2) (<> (text "マイクを投げてきた！")))))
                (if (== T 2)
                  (<>
                   (set-var I (? 3))
                   (if (== I 0) (<> (call F) (text "にささやいた！・・・☆○□◇☆！")))
                   (if (== I 1)
                     (<>
                      (text "泣いたふりをした！\n")
                      (call F)
                      (text "は、オロオロしてしまった！")
                      (set-var J 0)))
                   (if (== I 2)
                     (<> (text "逃げだした！") (set-reg: 0 1) (set-var J 0)))))
                (if (== T 3)
                  (<>
                   (set-var I (? 3))
                   (if (== I 0) (<> (text "強烈なパンチを放った！")))
                   (if (== I 1)
                     (<>
                      (set-var I (? 3))
                      (if (== I 0) (<> (text "空手")))
                      (if (== I 1) (<> (text "合気道")))
                      (if (== I 2) (<> (text "新体操")))
                      (text "の構えをした！\n")
                      (call F)
                      (text "は、おどろいた！")
                      (set-var J 0)))
                   (if (== I 2) (<> (call F) (text "を怪しいダンスをおどった！")))))
                (if (== T 4)
                  (<>
                   (set-var I (? 3))
                   (if (== I 0)
                     (<>
                      (call F)
                      (text "に数学の公式をささやいた！\n")
                      (call F)
                      (text "は、頭がいたくなった！")
                      (set-var J 0)))
                   (if (== I 1) (<> (text "メガネを光らせた！")))
                   (if (== I 2) (<> (call F) (text "にむずかしい本をみせた！")))))
                (if (== T 5)
                  (<>
                   (set-var I (? 3))
                   (if (== I 0) (<> (text "泡を投げつけてきた！まっ！前が見えない！")))
                   (if (== I 1) (<> (text "シャボンにかくれた！どこにいるのかわからない！")))
                   (if (== I 2)
                     (<>
                      (set-var I (? 4))
                      (if (== I 0) (<> (text "せっけん")))
                      (if (== I 1) (<> (text "タオル")))
                      (if (== I 2) (<> (text "ふろおけ")))
                      (if (== I 3) (<> (text "すけべいす")))
                      (text "を投げつけてきた。")))))
                (if (== T 6)
                  (<>
                   (set-var I (? 3))
                   (if (== I 0)
                     (<>
                      (if-else (== (? 2) 1) (<> (text "たま")) (<> (text "バット")))
                      (text "をにぎった！・・・　ギャー！")))
                   (if (== I 1) (<> (text "金属バットでなぐりかかってきた！")))
                   (if (== I 2) (<> (text "ボールをなげつけてきた！　パコッ！")))))
                (if (== T 7)
                  (<>
                   (set-var I (? 3))
                   (if (== I 0) (<> (call F) (text "のにささやいた！・・・☆○□◇☆！")))
                   (if (== I 1) (<> (text "大胆なポーズをとった！")))
                   (if (== I 2)
                     (<>
                      (call F)
                      (text "を怪しい目つきで見つめた！")
                      (set-var J (* J 2))))))))))))
       (wait 50)
       (if (!= J 0)
         (<>
          (text "\n")
          (call F)
          (text "は、")
          (set-arr~ @ 7 31)
          (text (number J) "のダメージをうけた！")
          (if-else (> J (~ M 0))
            (<>
             (set-arr~ M 0 0)
             (wait 150)
             (clear)
             (call F)
             (text "は、死んでしまった")
             (wait)
             (set-reg: 1 1)
             (break))
            (<> (set-arr~ M 0 (- (~ M 0) J))))
          (wait 150)))))))
 (define-proc 12
   (<>
    (if (== (: 1) 0)
      (<>
       (text-color 5)
       (clear)
       (text "アイテムを使った。\n")
       (wait 50)
       (text "しかし、何も起こらなかった。")
       (wait 150)))))
 (set-arr~ @ 2 7168)
 (set-reg: 0 0)
 (set-reg: 1 0)
 (set-reg: 2 0)
 (window 11 155 68 187)
 (text-color 7)
 (clear)
 (call G)
 (text "があらわれた！")
 (wait 50)
 (recover)
 (image "B_WAKU.PIC")
 (recover)
 (image A)
 (clear)
 (call G)
 (text "：あなたが、この学園に送り込まれてきた")
 (call F)
 (text "ね。残念だけどあなたには、力ずくでもこの学園から手を引いてもらうわよ！")
 (while
  (&& (!= (~ M 0) 0) (!= (~ E 0) 0) (== (: 0) 0))
  (<>
   (while
    (== 1 1)
    (<>
     (set-var V 0)
     (set-var N 0)
     (window 38 24 65 111)
     (text-color 7)
     (clear)
     (menu (<.> (text "たたかう") (text "にげる") (text "どうぐ")))
     (set-var V S)
     (if (== V 0) (<> (continue)))
     (if (== V 1) (<> (break)))
     (if (== V 2) (<> (break)))
     (if (== V 3)
       (<>
        (clear 0)
        (menu
         (<>
          (cond
           ((== (: 10) 1) (<> (text "水色のかぎ")))
           ((== (: 11) 1) (<> (text "赤色のかぎ")))
           ((== (: 12) 1) (<> (text "朱色のかぎ")))
           ((== (: 13) 1) (<> (text "白色のかぎ")))
           ((== (: 14) 1) (<> (text "亜美のメモ")))
           ((== (: 15) 1) (<> (text "精力剤・仁王立ち")))
           ((== (: 16) 1) (<> (text "なんと性拳の奥義書")))
           ((== (: 17) 1) (<> (text "奥義・☆☆☆☆☆☆")))
           ((== (: 18) 1) (<> (text "奥義・☆☆☆☆☆☆")))
           ((== (: 19) 1) (<> (text "奥義・☆☆☆☆☆☆")))
           ((== (: 20) 1) (<> (text "奥義・☆☆☆☆☆☆"))))))
        (set-var N S)
        (if (== N 0) (<> (continue)))
        (break)))))
   (window 11 155 68 187)
   (clear 0)
   (if (== V 1)
     (<>
      (if-else (> (+ (~ M 3) (? 10)) (+ (~ E 3) (? 1)))
        (<> (com 10) (com 11))
        (<> (com 11) (com 10)))))
   (if (== V 2)
     (<>
      (if-else (> (? 10) 5)
        (<> (text "へっへっへっ！にげたぜ！") (wait 100) (break))
        (<> (text "けげっ！逃げられない！") (wait 100) (clear) (com 11)))))
   (if (== V 3)
     (<>
      (if-else (> (+ (~ M 3) (? 10)) (+ (~ E 3) (? 1)))
        (<> (com 12) (com 11))
        (<> (com 11) (com 12)))))))
 (if (== (~ E 0) 0)
   (<>
    (cond
     ((== (: 51) 3)
      (<>
       (clear)
       (text #:color 6 "この時計をあげるから許して・・・")
       (wait)
       (clear)
       (set-reg: 23 1)))
     ((== (: 52) 2)
      (<>
       (clear)
       (text #:color 7 "ＬＥＶＥＬが３いじょうになったよーーーん。")
       (wait)
       (clear)
       (set-reg: 52 3)))
     ((== (: 52) 4)
      (<>
       (clear)
       (text #:color 3 "えっ、赤いノートならさっきゴミに捨てたわよ！")
       (wait)
       (clear)
       (text #:color 7 "げろげろ！それじゃあ、今頃は・・・")
       (wait)
       (clear)
       (text #:color 3 "そうね。焼却炉の火の中ね。")
       (wait)
       (clear)
       (set-reg: 52 5)))
     (else (<> (clear) (text #:color 6 "むふふ？") (wait) (clear)))))))