(mes
 (meta (engine 'AI1) (charset "english"))
 (set-arr~ @ 2 8192)
 (set-arr~ @ 1 45056)
 (window 0 0 79 199)
 (text-color 7)
 (clear)
 (set-arr~ @ 9 6664)
 (set-var I 0)
 (while
  (!= I 8)
  (<>
   (set-arr~ @ (+ (* I 2) 10) 39)
   (set-arr~ @ (+ (* I 2) 11) (+ 28 (* I 10)))
   (set-var I (+ I 1))))
 (set-arr~ @ 7 271)
 (set-var P 34850)
 (load "move.com" 34816)
 (set-arr~ M 0 200)
 (set-arr~ M 1 50)
 (set-arr~ M 2 20)
 (set-arr~ M 3 50)
 (set-arr~ L 0 1)
 (set-arr~ L 1 200)
 (recover)
 (image "ROYAL.PIC")
 (wait)
 (load "WALK.MU" (~ @ 1))
 (slot 1)
 (recover)
 (image "WAKU.PIC")
 (animate 1 22 6 137 61)
 (recover)
 (image "OPEN.PIC")
 (animate 0 22 6 137 61)
 ((cmd 185) 2 0 "Ê¶¾.ANI")
 ((cmd 185) 3 0 "².±.")
 ((cmd 185) 4 0 5)
 (window 11 155 68 187)
 (text-color 5)
 (clear)
 (text "Good morning, kid. How are you doing today?")
 (wait)
 (text-color 7)
 (clear)
 (text "It's awful, boss. I got no sleep!")
 (wait)
 (clear)
 (text "Well, there is a major time zone difference from here to there.")
 (clear)
 (text "Maybe I should consider that next time...")
 (wait)
 (text-color 5)
 (clear)
 (text "Ha! Don't jibber jabber too much. You know, getting up early is best.")
 (wait)
 (text-color 7)
 (clear)
 (text "Whatever. What's the mission this time?")
 (wait)
 (text-color 5)
 (clear)
 (text "Well, you know what St. Stoic Academy is?")
 (wait)
 (text-color 7)
 (clear)
 (text "It is a pretty high standard educational institution.")
 (clear)
 (text "You have to excel in either academics or sports to be admitted into there.")
 (wait)
 (text-color 5)
 (clear)
 (text "Correct. And the newspaper's club director requested me to send in a spy to investigate this school.")
 (wait)
 (text-color 7)
 (clear)
 (text "Didn't you already carry out an investigation? You told me about that a while ago.")
 (wait)
 (text-color 5)
 (clear)
 (text "Yes, and oddly we abruptly lost contact with our spy 3 days ago.")
 (wait)
 (text-color 7)
 (clear)
 (text "Who was that spy again?")
 (wait)
 (text-color 5)
 (clear)
 (text "Keiko. According to our cilent, there's this organization based in the school that's preying on the students.")
 (wait)
 (text-color 7)
 (clear)
 (text "Keiko, huh. Well, what do we know now?")
 (wait)
 (text-color 5)
 (clear)
 (text "It turns out the organization was the student council! No wonder I couldn't go over and ask them about the issue!")
 (wait)
 (text-color 7)
 (clear)
 (text "So, what am I supposed to do here?")
 (wait)
 (text-color 5)
 (clear)
 (text "Simple. Sneak in, save Keiko, and take down the student council.")
 (wait)
 (text-color 7)
 (clear)
 (text "でも、あそこは女子高ですよ。まさか俺に女装しろっていうんじゃ・・・")
 (wait)
 (text-color 5)
 (clear)
 (text "安心せい。お前にはちゃんと用務員のポストを用意してある・・・んっ？・・・なんだ？そのとっても不満そうな顔は？")
 (wait)
 (text-color 7)
 (clear)
 (text "・・・ねぇ、ボス。用務員じゃなくてせめて学校の先生かなんかにしてもらえないんですかねぇ？")
 (wait)
 (text-color 5)
 (clear)
 (text "へん！生徒よりも出来のわるい奴が先生なんかできるわけないじゃろ！お前は用務員で十分じゃ。")
 (wait)
 (text-color 7)
 (clear)
 (text "ひでー！そりゃ差別ってもんですよ。いいんだ、そのうちボスのわら人形を作って牛の刻まいりをしちゃうからね。")
 (wait)
 (text-color 5)
 (clear)
 (text "えーい、いちいちうるさいやつめ！さっさと、仕事に取りかかれ！・・・")
 (wait 100)
 (clear)
 ((cmd 185) 4 0 9)
 ((cmd 185) 3 0 "³.´.µ.¶.·.¸.¹.º.».")
 ((cmd 185) 0 0 1)
 (text "Ugh! You son of a bitch!")
 (wait)
 (text-color 6)
 (clear)
 (text "Hey boss! Get back here!")
 (wait)
 (clear)
 (text-color 5)
 ((cmd 185) 2 0 "¶ÞÒÝ.ANI")
 ((cmd 185) 3 0 "±.².³.´.µ.¶.·")
 ((cmd 185) 0 0 1)
 (text "......")
 (wait)
 (clear)
 (text
  #:color
  6
  "あぁ、消えちゃった。まったく、まだ聞きたいことはいっぱいあったのになぁ。まぁ、とにかく聖ストカイック学園にいってみるか。")
 (wait)
 (clear)
 (slot 0)
 (set-var I 1)
 (set-arr~ @ 0 8192)
 (mes-jump "GAKKO.MES"))